// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { EventSourceConfig } from "../../types/sandbox/EventSourceConfig";

export const EventSourceConfigSchema = z.object({ "dateRange": z.object({ "end": z.string(), "start": z.string() }), "eventTypeFilter": z.array(z.string()), "sourceFilter": z.array(z.string()) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _EventSourceConfigInferred = z.infer<typeof EventSourceConfigSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _EventSourceConfigDriftCheck = _EventSourceConfigInferred & EventSourceConfig;
