// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FilterConfig } from "../../types/sandbox/FilterConfig";

export const FilterConfigSchema = z.object({ "rules": z.array(z.object({ "field": z.string(), "id": z.string(), "operator": z.string(), "value": z.string() })) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FilterConfigInferred = z.infer<typeof FilterConfigSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FilterConfigDriftCheck = _FilterConfigInferred & FilterConfig;
