// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FilterRule } from "../../types/sandbox/FilterRule";

export const FilterRuleSchema = z.object({ "field": z.string(), "id": z.string(), "operator": z.string(), "value": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FilterRuleInferred = z.infer<typeof FilterRuleSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FilterRuleDriftCheck = _FilterRuleInferred & FilterRule;
