// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { GeneratorConfig } from "../../types/sandbox/GeneratorConfig";

export const GeneratorConfigSchema = z.object({ "count": z.number().int().gte(0), "eventTypes": z.array(z.string()), "intervalMs": z.number().int().gte(0), "sourceTypes": z.array(z.string()), "variationLevel": z.number() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _GeneratorConfigInferred = z.infer<typeof GeneratorConfigSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _GeneratorConfigDriftCheck = _GeneratorConfigInferred & GeneratorConfig;
