// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { GraphEditValidationError } from "../../types/sandbox/GraphEditValidationError";

export const GraphEditValidationErrorSchema = z.object({ "commandIndex": z.union([z.number().int().gte(0), z.null()]).optional(), "message": z.string(), "path": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _GraphEditValidationErrorInferred = z.infer<typeof GraphEditValidationErrorSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _GraphEditValidationErrorDriftCheck = _GraphEditValidationErrorInferred & GraphEditValidationError;
