// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { OutputConfig } from "../../types/sandbox/OutputConfig";

export const OutputConfigSchema = z.object({ "fileFormat": z.enum(["jsonl","csv"]), "includedFields": z.array(z.string()), "outputType": z.enum(["sse","webhook","file","console"]), "transformTemplate": z.string(), "webhookUrl": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _OutputConfigInferred = z.infer<typeof OutputConfigSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _OutputConfigDriftCheck = _OutputConfigInferred & OutputConfig;
