// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxValidationIssue } from "../../types/sandbox/SandboxValidationIssue";

export const SandboxValidationIssueSchema = z.object({ "message": z.string(), "path": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxValidationIssueInferred = z.infer<typeof SandboxValidationIssueSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxValidationIssueDriftCheck = _SandboxValidationIssueInferred & SandboxValidationIssue;
