// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxOutputType } from "../../types/sandbox/SandboxOutputType";

export const SandboxOutputTypeSchema = z.enum(["sse","webhook","file","console"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxOutputTypeInferred = z.infer<typeof SandboxOutputTypeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxOutputTypeDriftCheck = _SandboxOutputTypeInferred & SandboxOutputType;
