// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxAiChatRole } from "../../types/sandbox/SandboxAiChatRole";

export const SandboxAiChatRoleSchema = z.enum(["user","assistant"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxAiChatRoleInferred = z.infer<typeof SandboxAiChatRoleSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxAiChatRoleDriftCheck = _SandboxAiChatRoleInferred & SandboxAiChatRole;
