// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxAiChatMessage } from "../../types/sandbox/SandboxAiChatMessage";

export const SandboxAiChatMessageSchema = z.object({ "content": z.string(), "role": z.enum(["user","assistant"]) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxAiChatMessageInferred = z.infer<typeof SandboxAiChatMessageSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxAiChatMessageDriftCheck = _SandboxAiChatMessageInferred & SandboxAiChatMessage;
