// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxFileFormat } from "../../types/sandbox/SandboxFileFormat";

export const SandboxFileFormatSchema = z.enum(["jsonl","csv"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxFileFormatInferred = z.infer<typeof SandboxFileFormatSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxFileFormatDriftCheck = _SandboxFileFormatInferred & SandboxFileFormat;
