// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxNodeData } from "../../types/sandbox/SandboxNodeData";

export const SandboxNodeDataSchema = z.union([z.object({ "config": z.object({ "dateRange": z.object({ "end": z.string(), "start": z.string() }), "eventTypeFilter": z.array(z.string()), "sourceFilter": z.array(z.string()) }), "label": z.string(), "nodeType": z.literal("event-source") }), z.object({ "config": z.object({ "rules": z.array(z.object({ "field": z.string(), "id": z.string(), "operator": z.string(), "value": z.string() })) }), "label": z.string(), "nodeType": z.literal("filter") }), z.object({ "config": z.object({ "fileFormat": z.enum(["jsonl","csv"]), "includedFields": z.array(z.string()), "outputType": z.enum(["sse","webhook","file","console"]), "transformTemplate": z.string(), "webhookUrl": z.string() }), "label": z.string(), "nodeType": z.literal("output") }), z.object({ "config": z.object({ "count": z.number().int().gte(0), "eventTypes": z.array(z.string()), "intervalMs": z.number().int().gte(0), "sourceTypes": z.array(z.string()), "variationLevel": z.number() }), "label": z.string(), "nodeType": z.literal("generator") })])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxNodeDataInferred = z.infer<typeof SandboxNodeDataSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxNodeDataDriftCheck = _SandboxNodeDataInferred & SandboxNodeData;
