// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxValidationResponse } from "../../types/sandbox/SandboxValidationResponse";

export const SandboxValidationResponseSchema = z.object({ "issues": z.array(z.object({ "message": z.string(), "path": z.string() })), "ok": z.boolean() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxValidationResponseInferred = z.infer<typeof SandboxValidationResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxValidationResponseDriftCheck = _SandboxValidationResponseInferred & SandboxValidationResponse;
