// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxNodePosition } from "../../types/sandbox/SandboxNodePosition";

export const SandboxNodePositionSchema = z.object({ "x": z.number(), "y": z.number() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxNodePositionInferred = z.infer<typeof SandboxNodePositionSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxNodePositionDriftCheck = _SandboxNodePositionInferred & SandboxNodePosition;
