// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxEdgeDto } from "../../types/sandbox/SandboxEdgeDto";

export const SandboxEdgeDtoSchema = z.object({ "id": z.string(), "source": z.string(), "target": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxEdgeDtoInferred = z.infer<typeof SandboxEdgeDtoSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxEdgeDtoDriftCheck = _SandboxEdgeDtoInferred & SandboxEdgeDto;
