// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { SandboxDateRange } from "../../types/sandbox/SandboxDateRange";

export const SandboxDateRangeSchema = z.object({ "end": z.string(), "start": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _SandboxDateRangeInferred = z.infer<typeof SandboxDateRangeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _SandboxDateRangeDriftCheck = _SandboxDateRangeInferred & SandboxDateRange;
