// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPreparedCall } from "./AgentPreparedCall";
import type { AgentRunError } from "./AgentRunError";
import type { AgentRunOperation } from "./AgentRunOperation";
import type { AgentRunResponse } from "./AgentRunResponse";
import type { AgentRunStatus } from "./AgentRunStatus";
import type { AgentToolCall } from "./AgentToolCall";

export type AgentRun = { schemaVersion: string, runId: string, artifactId: string, configHash: string, operation: AgentRunOperation, startedAt: string, finishedAt?: string, durationMs?: number, status: AgentRunStatus, inputHash?: string, callOptionsHash?: string, preparedCall?: AgentPreparedCall, response?: AgentRunResponse, toolCalls: Array<AgentToolCall>, trace?: Record<string, string>, error?: AgentRunError, };
