// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunUsage } from "./AgentRunUsage";

export type AgentRunResponse = { id?: string, modelId?: string, bodyHash?: string, finishReason?: string, usage?: AgentRunUsage, providerMetadata?: Record<string, unknown>, modelMetadata?: Record<string, unknown>, 
/**
 * Subset of headers preserved for the run drawer.
 */
headers?: Record<string, string>, };
