// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentArtifact } from "./AgentArtifact";
import type { AgentVersionStatus } from "./AgentVersionStatus";

export type AgentVersionSummary = { artifact: AgentArtifact, runCount: number, 
/**
 * Successful runs / total runs (0..1).
 */
successRate: number, meanDurationMs?: number, p95DurationMs?: number, totalTokens?: number, lastRunAt?: string, resolvedModelIds: Array<string>, status: AgentVersionStatus, };
