// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentPolicy = { maxSteps?: number, allowedTools?: Array<string>, approvalRequired?: Array<string>, metadata?: Record<string, unknown>, };
