// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentDriftEntry = { observedAt: string, runId: string, artifactId: string, 
/**
 * Short verb summarizing the change.
 */
summary: string, before?: Record<string, unknown>, after?: Record<string, unknown>, };
