// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContractPreview } from "./AgentContractPreview";
import type { AgentFramework } from "./AgentFramework";
import type { AgentKnowledgeSource } from "./AgentKnowledgeSource";
import type { AgentModelDescriptor } from "./AgentModelDescriptor";
import type { AgentPolicy } from "./AgentPolicy";
import type { AgentProvenance } from "./AgentProvenance";
import type { AgentToolDefinition } from "./AgentToolDefinition";
import type { AgentWorkflowGraph } from "./AgentWorkflowGraph";

export type AgentArtifact = { 
/**
 * Schema marker — frontend code matches against the literal
 * string `"agent-artifact-v1"` so newer payloads can co-exist
 * when we evolve the shape.
 */
schemaVersion: string, name: string, version: string, artifactId: string, description?: string, framework: AgentFramework, instructions?: string, instructionsHash?: string, model: AgentModelDescriptor, providerOptions?: Record<string, unknown>, providerOptionsHash?: string, tools: Array<AgentToolDefinition>, policy?: AgentPolicy, metadata?: Record<string, unknown>, provenance: AgentProvenance, configHash: string, 
/**
 * Compact preview of the input contract this artifact expects.
 */
inputContractPreview?: AgentContractPreview, 
/**
 * Compact preview of the output contract this artifact emits.
 */
outputContractPreview?: AgentContractPreview, knowledgeSources?: Array<AgentKnowledgeSource>, workflowGraphPreview?: AgentWorkflowGraph, };
