// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKnowledgeKind } from "./AgentKnowledgeKind";

export type AgentKnowledgeSource = { id: string, label: string, kind: AgentKnowledgeKind, 
/**
 * Optional human-readable size hint, e.g. "12.4k docs".
 */
sizeLabel?: string, 
/**
 * Optional jump-out link.
 */
href?: string, };
