// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRunUsage = { inputTokens?: number, outputTokens?: number, reasoningTokens?: number, cachedInputTokens?: number, totalTokens?: number, };
