// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentToolDefinition = { name: string, description?: string, inputSchemaHash?: string, 
/**
 * Optional small input-schema preview rendered in the Tools tab.
 */
inputSchemaPreview?: Record<string, unknown>, metadata?: Record<string, unknown>, };
