// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentProvenance = { aiSdkVersion?: string, frameworkVersion?: string, gitSha?: string, dependencyLockHash?: string, createdAt: string, publishedBy?: string, };
