// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRun } from "./AgentRun";
import type { AgentSummary } from "./AgentSummary";
import type { AgentVersionSummary } from "./AgentVersionSummary";
import type { HashIndexEntry } from "./HashIndexEntry";

export type AgentSnapshot = { summary: AgentSummary, versions: Array<AgentVersionSummary>, runs: Array<AgentRun>, hashIndex: Array<HashIndexEntry>, };
