// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunError } from "./AgentRunError";
import type { AgentRunStatus } from "./AgentRunStatus";

export type AgentToolCall = { callId: string, toolName: string, startedAt: string, finishedAt?: string, durationMs?: number, status: AgentRunStatus, argsHash?: string, resultHash?: string, 
/**
 * Optional small preview of the tool args.
 */
argsPreview?: Record<string, unknown>, resultPreview?: Record<string, unknown>, error?: AgentRunError, };
