// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact preview of an input or output contract for the artifact's
 * Capabilities section.
 */
export type AgentContractPreview = { 
/**
 * One-line shape summary.
 */
schemaSummary?: string, 
/**
 * Representative example payload.
 */
example?: unknown, };
