// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentWorkflowNodeKind } from "./AgentWorkflowNodeKind";

export type AgentWorkflowNode = { id: string, kind: AgentWorkflowNodeKind, label: string, 
/**
 * Optional tool name reference for tool nodes.
 */
toolName?: string, };
