// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentWorkflowEdge = { from: string, to: string, 
/**
 * Optional short label rendered along the edge.
 */
label?: string, };
