// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashDomain } from "./HashDomain";

export type AgentManifestDiffRow = { domain: HashDomain, 
/**
 * JSON path within the domain.
 */
path: string, before: unknown, after: unknown, 
/**
 * True when before/after are deep-equal.
 */
unchanged: boolean, };
