// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Framework label. Multi-word kebab-case to match the existing TS
 * union (`vercel-ai-sdk`, `openai-agents-python`, etc.).
 */
export type AgentFramework = "vercel-ai-sdk" | "openai-agents" | "langchain" | "mastra" | "langchain-python" | "llamaindex" | "crewai" | "smolagents" | "pydantic-ai" | "strands" | "google-adk" | "openai-agents-python" | "autogen";
