// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentWorkflowEdge } from "./AgentWorkflowEdge";
import type { AgentWorkflowNode } from "./AgentWorkflowNode";

export type AgentWorkflowGraph = { nodes: Array<AgentWorkflowNode>, edges: Array<AgentWorkflowEdge>, };
