// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFramework } from "./AgentFramework";
import type { AgentModelDescriptor } from "./AgentModelDescriptor";

export type AgentSummary = { name: string, description?: string, framework: AgentFramework, latestVersion: string, versionCount: number, totalRuns: number, successRate: number, lastRunAt?: string, 
/**
 * Last drift event, if any.
 */
lastDriftAt?: string, modelLabel: string, model: AgentModelDescriptor, owner?: string, environment?: string, purpose?: string, personaSummary?: string, capabilityTags?: Array<string>, category?: string, playgroundUrl?: string, runbookUrl?: string, };
