// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFramework } from "./AgentFramework";
import type { HashDomain } from "./HashDomain";

export type HashIndexEntry = { hash: string, kind: HashDomain, artifactId?: string, runId?: string, framework?: AgentFramework, path: string, 
/**
 * Stringified preview of the value rendered next to the hash.
 */
preview?: string, observedAt: string, };
