// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 13 hash domains the wrapper tracks. The first eight describe the
 * artifact (config-time); the last five describe a run (observed at
 * call-time).
 */
export type HashDomain = "agent.root" | "prompt" | "model.contract" | "provider.options" | "tool.contract" | "runtime.policy" | "dependency" | "knowledge.contract" | "workflow.graph" | "effective.run" | "provider.observation" | "operational" | "output";
