// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentEndpointConfig } from "../../types/saas/AgentEndpointConfig";

export const AgentEndpointConfigSchema = z.object({ "authHeaderName": z.union([z.string(), z.null()]).optional(), "authSecretEncrypted": z.union([z.string(), z.null()]).optional(), "authType": z.string(), "basicUsername": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "customHeadersJson": z.any().optional(), "endpointUrl": z.union([z.string(), z.null()]).optional(), "id": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentEndpointConfigInferred = z.infer<typeof AgentEndpointConfigSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentEndpointConfigDriftCheck = _AgentEndpointConfigInferred & AgentEndpointConfig;
