// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AuditLog } from "../../types/saas/AuditLog";

export const AuditLogSchema = z.object({ "action": z.string(), "actor": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.union([z.string(), z.null()]).optional(), "id": z.string(), "invocationId": z.union([z.string(), z.null()]).optional(), "payload": z.any().optional(), "runId": z.union([z.string(), z.null()]).optional(), "tenantId": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AuditLogInferred = z.infer<typeof AuditLogSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AuditLogDriftCheck = _AuditLogInferred & AuditLog;
