// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { Connection } from "../../types/saas/Connection";

export const ConnectionSchema = z.object({ "accessToken": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "expiresAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "id": z.string(), "metadata": z.any().optional(), "nangoConnectionId": z.union([z.string(), z.null()]).optional(), "provider": z.string(), "refreshToken": z.union([z.string(), z.null()]).optional(), "status": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionInferred = z.infer<typeof ConnectionSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionDriftCheck = _ConnectionInferred & Connection;
