// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { IntegrationSync } from "../../types/saas/IntegrationSync";

export const IntegrationSyncSchema = z.object({ "configuredProps": z.any().optional(), "connectionId": z.string(), "createdAt": z.string().datetime({ offset: true }), "id": z.string(), "lastSyncAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "nangoSyncId": z.string(), "status": z.string(), "syncCursor": z.union([z.string(), z.null()]).optional(), "syncName": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _IntegrationSyncInferred = z.infer<typeof IntegrationSyncSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _IntegrationSyncDriftCheck = _IntegrationSyncInferred & IntegrationSync;
