// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { Invitation } from "../../types/saas/Invitation";

export const InvitationSchema = z.object({ "acceptedAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "email": z.string(), "expiresAt": z.string().datetime({ offset: true }), "id": z.string(), "invitedBy": z.string(), "role": z.enum(["owner","admin","member"]), "tenantId": z.string(), "token": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _InvitationInferred = z.infer<typeof InvitationSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _InvitationDriftCheck = _InvitationInferred & Invitation;
