// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { MembershipStatus } from "../../types/saas/MembershipStatus";

export const MembershipStatusSchema = z.enum(["pending","active","inactive"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _MembershipStatusInferred = z.infer<typeof MembershipStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _MembershipStatusDriftCheck = _MembershipStatusInferred & MembershipStatus;
