// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { RunStatus } from "../../types/saas/RunStatus";

export const RunStatusSchema = z.enum(["pending","processing","completed","failed","requires_human"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _RunStatusInferred = z.infer<typeof RunStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _RunStatusDriftCheck = _RunStatusInferred & RunStatus;
