// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { TenantMembership } from "../../types/saas/TenantMembership";

export const TenantMembershipSchema = z.object({ "createdAt": z.string().datetime({ offset: true }), "id": z.string(), "role": z.enum(["owner","admin","member"]), "status": z.enum(["pending","active","inactive"]), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }), "userId": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _TenantMembershipInferred = z.infer<typeof TenantMembershipSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _TenantMembershipDriftCheck = _TenantMembershipInferred & TenantMembership;
