// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { Tenant } from "../../types/saas/Tenant";

export const TenantSchema = z.object({ "createdAt": z.string().datetime({ offset: true }), "id": z.string(), "name": z.string(), "slug": z.string(), "stripeCustomerId": z.union([z.string(), z.null()]).optional(), "stripePriceId": z.union([z.string(), z.null()]).optional(), "stripeSubscriptionStatus": z.union([z.string(), z.null()]).optional(), "updatedAt": z.string().datetime({ offset: true }), "workosOrganizationId": z.union([z.string().describe("Linked WorkOS Organization id. Populated lazily during the WorkOS importer (Phase 1) or eagerly via `provisionWorkspace` (Phase 2)."), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _TenantInferred = z.infer<typeof TenantSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _TenantDriftCheck = _TenantInferred & Tenant;
