// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { User } from "../../types/saas/User";

export const UserSchema = z.object({ "authProvider": z.string(), "createdAt": z.string().datetime({ offset: true }), "createdVia": z.union([z.string().describe("Free-form provenance tag. One of `self_serve`, `invite`, `scim`, `import`. Used by the F.2 admin user-detail surface and to bucket audit reports across provisioning paths."), z.null()]).optional(), "email": z.string(), "emailVerifiedAt": z.union([z.string().datetime({ offset: true }).describe("Mirror of WorkOS `emailVerified` state. Mirrored at JIT-create and SCIM-sync time so audit code can answer \"did this person ever verify their email?\" without round-tripping to WorkOS."), z.null()]).optional(), "id": z.string(), "name": z.union([z.string(), z.null()]).optional(), "password": z.union([z.string(), z.null()]).optional(), "role": z.enum(["owner","admin","member"]), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }), "workosUserId": z.union([z.string().describe("Linked WorkOS user id (`user_…`). Populated by the importer for pre-existing accounts and at JIT-create time for new accounts."), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UserInferred = z.infer<typeof UserSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UserDriftCheck = _UserInferred & User;
