// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { UserRole } from "../../types/saas/UserRole";

export const UserRoleSchema = z.enum(["owner","admin","member"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UserRoleInferred = z.infer<typeof UserRoleSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UserRoleDriftCheck = _UserRoleInferred & UserRole;
