// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { EntitlementSnapshot } from "../../types/feature-access/EntitlementSnapshot";

export const EntitlementSnapshotSchema = z.object({ "enabled": z.boolean(), "key": z.enum(["runs","connections","auditLog","agentEndpointConfig","sandbox","workflowFilters"]), "limit": z.union([z.number().int(), z.null()]).optional(), "source": z.enum(["default","plan","globalOverride","tenantOverride","userOverride"]) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _EntitlementSnapshotInferred = z.infer<typeof EntitlementSnapshotSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _EntitlementSnapshotDriftCheck = _EntitlementSnapshotInferred & EntitlementSnapshot;
