// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { EntitlementKey } from "../../types/feature-access/EntitlementKey";

export const EntitlementKeySchema = z.enum(["runs","connections","auditLog","agentEndpointConfig","sandbox","workflowFilters"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _EntitlementKeyInferred = z.infer<typeof EntitlementKeySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _EntitlementKeyDriftCheck = _EntitlementKeyInferred & EntitlementKey;
