// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagDefinition } from "../../types/feature-access/FeatureFlagDefinition";

export const FeatureFlagDefinitionSchema = z.object({ "createdAt": z.string().datetime({ offset: true }), "defaultEnabled": z.boolean(), "description": z.string(), "enabled": z.boolean(), "expiresAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "flagType": z.enum(["release","ops","experiment","entitlement"]), "key": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "owner": z.string(), "updatedAt": z.string().datetime({ offset: true }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagDefinitionInferred = z.infer<typeof FeatureFlagDefinitionSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagDefinitionDriftCheck = _FeatureFlagDefinitionInferred & FeatureFlagDefinition;
