// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagScope } from "../../types/feature-access/FeatureFlagScope";

export const FeatureFlagScopeSchema = z.enum(["global","tenant","user"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagScopeInferred = z.infer<typeof FeatureFlagScopeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagScopeDriftCheck = _FeatureFlagScopeInferred & FeatureFlagScope;
