// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagType } from "../../types/feature-access/FeatureFlagType";

export const FeatureFlagTypeSchema = z.enum(["release","ops","experiment","entitlement"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagTypeInferred = z.infer<typeof FeatureFlagTypeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagTypeDriftCheck = _FeatureFlagTypeInferred & FeatureFlagType;
