// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagKey } from "../../types/feature-access/FeatureFlagKey";

export const FeatureFlagKeySchema = z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagKeyInferred = z.infer<typeof FeatureFlagKeySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagKeyDriftCheck = _FeatureFlagKeyInferred & FeatureFlagKey;
