// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagSnapshot } from "../../types/feature-access/FeatureFlagSnapshot";

export const FeatureFlagSnapshotSchema = z.object({ "definition": z.object({ "createdAt": z.string().datetime({ offset: true }), "defaultEnabled": z.boolean(), "description": z.string(), "enabled": z.boolean(), "expiresAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "flagType": z.enum(["release","ops","experiment","entitlement"]), "key": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "owner": z.string(), "updatedAt": z.string().datetime({ offset: true }) }), "enabled": z.boolean(), "key": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "overrideEnabled": z.union([z.boolean(), z.null()]).optional(), "source": z.enum(["default","plan","globalOverride","tenantOverride","userOverride"]) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagSnapshotInferred = z.infer<typeof FeatureFlagSnapshotSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagSnapshotDriftCheck = _FeatureFlagSnapshotInferred & FeatureFlagSnapshot;
