// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureFlagOverride } from "../../types/feature-access/FeatureFlagOverride";

export const FeatureFlagOverrideSchema = z.object({ "createdAt": z.string().datetime({ offset: true }), "enabled": z.boolean(), "flagKey": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "id": z.string(), "reason": z.union([z.string(), z.null()]).optional(), "rolloutPercentage": z.union([z.number().int(), z.null()]).optional(), "scopeId": z.string(), "scopeType": z.enum(["global","tenant","user"]), "updatedAt": z.string().datetime({ offset: true }), "variant": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureFlagOverrideInferred = z.infer<typeof FeatureFlagOverrideSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureFlagOverrideDriftCheck = _FeatureFlagOverrideInferred & FeatureFlagOverride;
