// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureValueSource } from "../../types/feature-access/FeatureValueSource";

export const FeatureValueSourceSchema = z.enum(["default","plan","globalOverride","tenantOverride","userOverride"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureValueSourceInferred = z.infer<typeof FeatureValueSourceSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureValueSourceDriftCheck = _FeatureValueSourceInferred & FeatureValueSource;
