// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { PlanId } from "../../types/feature-access/PlanId";

export const PlanIdSchema = z.enum(["free","starter","pro","enterprise","customEnterprise"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _PlanIdInferred = z.infer<typeof PlanIdSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _PlanIdDriftCheck = _PlanIdInferred & PlanId;
