// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentEndpointResponse } from "../../types/endpoints/AgentEndpointResponse";

export const AgentEndpointResponseSchema = z.object({ "config": z.union([z.object({ "authHeaderName": z.union([z.string(), z.null()]).optional(), "authSecretEncrypted": z.union([z.string(), z.null()]).optional(), "authType": z.string(), "basicUsername": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "customHeadersJson": z.any().optional(), "endpointUrl": z.union([z.string(), z.null()]).optional(), "id": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }) }), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentEndpointResponseInferred = z.infer<typeof AgentEndpointResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentEndpointResponseDriftCheck = _AgentEndpointResponseInferred & AgentEndpointResponse;
