// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AuditLogListResponse } from "../../types/endpoints/AuditLogListResponse";

export const AuditLogListResponseSchema = z.object({ "auditLogs": z.array(z.object({ "action": z.string(), "actor": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.union([z.string(), z.null()]).optional(), "id": z.string(), "invocationId": z.union([z.string(), z.null()]).optional(), "payload": z.any().optional(), "runId": z.union([z.string(), z.null()]).optional(), "tenantId": z.string() })), "limit": z.number().int().gte(0), "offset": z.number().int().gte(0) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AuditLogListResponseInferred = z.infer<typeof AuditLogListResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AuditLogListResponseDriftCheck = _AuditLogListResponseInferred & AuditLogListResponse;
