// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AuditLogParams } from "../../types/endpoints/AuditLogParams";

export const AuditLogParamsSchema = z.object({ "limit": z.union([z.number().int().gte(0), z.null()]).optional(), "offset": z.union([z.number().int().gte(0), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AuditLogParamsInferred = z.infer<typeof AuditLogParamsSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AuditLogParamsDriftCheck = _AuditLogParamsInferred & AuditLogParams;
