// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { CreateRunRequest } from "../../types/endpoints/CreateRunRequest";

export const CreateRunRequestSchema = z.object({ "contextPointers": z.any().optional(), "eventId": z.string(), "eventSnapshot": z.any().optional(), "invocationId": z.string(), "mode": z.union([z.string(), z.null()]).optional(), "workflowId": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _CreateRunRequestInferred = z.infer<typeof CreateRunRequestSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _CreateRunRequestDriftCheck = _CreateRunRequestInferred & CreateRunRequest;
