// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { DashboardStatsResponse } from "../../types/endpoints/DashboardStatsResponse";

export const DashboardStatsResponseSchema = z.object({ "activeConnections": z.number().int().gte(0), "completedRuns": z.number().int().gte(0), "failedRuns": z.number().int().gte(0), "pendingRuns": z.number().int().gte(0), "totalConnections": z.number().int().gte(0), "totalRuns": z.number().int().gte(0) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _DashboardStatsResponseInferred = z.infer<typeof DashboardStatsResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _DashboardStatsResponseDriftCheck = _DashboardStatsResponseInferred & DashboardStatsResponse;
