// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { DashboardActivityResponse } from "../../types/endpoints/DashboardActivityResponse";

export const DashboardActivityResponseSchema = z.object({ "activity": z.array(z.object({ "action": z.string(), "actor": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.union([z.string(), z.null()]).optional(), "id": z.string(), "invocationId": z.union([z.string(), z.null()]).optional(), "payload": z.any().optional(), "runId": z.union([z.string(), z.null()]).optional(), "tenantId": z.string() })) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _DashboardActivityResponseInferred = z.infer<typeof DashboardActivityResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _DashboardActivityResponseDriftCheck = _DashboardActivityResponseInferred & DashboardActivityResponse;
