// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { FeatureAccessResponse } from "../../types/endpoints/FeatureAccessResponse";

export const FeatureAccessResponseSchema = z.object({ "access": z.object({ "entitlements": z.array(z.object({ "enabled": z.boolean(), "key": z.enum(["runs","connections","auditLog","agentEndpointConfig","sandbox","workflowFilters"]), "limit": z.union([z.number().int(), z.null()]).optional(), "source": z.enum(["default","plan","globalOverride","tenantOverride","userOverride"]) })), "flags": z.array(z.object({ "definition": z.object({ "createdAt": z.string().datetime({ offset: true }), "defaultEnabled": z.boolean(), "description": z.string(), "enabled": z.boolean(), "expiresAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "flagType": z.enum(["release","ops","experiment","entitlement"]), "key": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "owner": z.string(), "updatedAt": z.string().datetime({ offset: true }) }), "enabled": z.boolean(), "key": z.enum(["sandbox","auditLog","agentEndpointConfig","workflowFilters"]), "overrideEnabled": z.union([z.boolean(), z.null()]).optional(), "source": z.enum(["default","plan","globalOverride","tenantOverride","userOverride"]) })), "planId": z.enum(["free","starter","pro","enterprise","customEnterprise"]) }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _FeatureAccessResponseInferred = z.infer<typeof FeatureAccessResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _FeatureAccessResponseDriftCheck = _FeatureAccessResponseInferred & FeatureAccessResponse;
