// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ListRunsResponse } from "../../types/endpoints/ListRunsResponse";

export const ListRunsResponseSchema = z.object({ "limit": z.number().int().gte(0), "offset": z.number().int().gte(0), "runs": z.array(z.object({ "agentRequest": z.any().optional(), "agentResponse": z.any().optional(), "contextPointers": z.any().optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.string(), "eventSnapshot": z.any().optional(), "humanDecision": z.any().optional(), "id": z.string(), "invocationId": z.string(), "mode": z.string(), "status": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }), "workflowId": z.union([z.string(), z.null()]).optional() })), "total": z.number().int().gte(0) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ListRunsResponseInferred = z.infer<typeof ListRunsResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ListRunsResponseDriftCheck = _ListRunsResponseInferred & ListRunsResponse;
