// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ListRunsParams } from "../../types/endpoints/ListRunsParams";

export const ListRunsParamsSchema = z.object({ "limit": z.union([z.number().int().gte(0), z.null()]).optional(), "offset": z.union([z.number().int().gte(0), z.null()]).optional(), "status": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ListRunsParamsInferred = z.infer<typeof ListRunsParamsSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ListRunsParamsDriftCheck = _ListRunsParamsInferred & ListRunsParams;
