// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { RunDetailResponse } from "../../types/endpoints/RunDetailResponse";

export const RunDetailResponseSchema = z.object({ "auditLogs": z.array(z.object({ "action": z.string(), "actor": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.union([z.string(), z.null()]).optional(), "id": z.string(), "invocationId": z.union([z.string(), z.null()]).optional(), "payload": z.any().optional(), "runId": z.union([z.string(), z.null()]).optional(), "tenantId": z.string() })), "run": z.object({ "agentRequest": z.any().optional(), "agentResponse": z.any().optional(), "contextPointers": z.any().optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.string(), "eventSnapshot": z.any().optional(), "humanDecision": z.any().optional(), "id": z.string(), "invocationId": z.string(), "mode": z.string(), "status": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }), "workflowId": z.union([z.string(), z.null()]).optional() }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _RunDetailResponseInferred = z.infer<typeof RunDetailResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _RunDetailResponseDriftCheck = _RunDetailResponseInferred & RunDetailResponse;
