// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { RunResponse } from "../../types/endpoints/RunResponse";

export const RunResponseSchema = z.object({ "run": z.object({ "agentRequest": z.any().optional(), "agentResponse": z.any().optional(), "contextPointers": z.any().optional(), "createdAt": z.string().datetime({ offset: true }), "eventId": z.string(), "eventSnapshot": z.any().optional(), "humanDecision": z.any().optional(), "id": z.string(), "invocationId": z.string(), "mode": z.string(), "status": z.string(), "tenantId": z.string(), "updatedAt": z.string().datetime({ offset: true }), "workflowId": z.union([z.string(), z.null()]).optional() }) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _RunResponseInferred = z.infer<typeof RunResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _RunResponseDriftCheck = _RunResponseInferred & RunResponse;
