// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { TenantResponse } from "../../types/endpoints/TenantResponse";

export const TenantResponseSchema = z.object({ "tenant": z.union([z.object({ "createdAt": z.string().datetime({ offset: true }), "id": z.string(), "name": z.string(), "slug": z.string(), "stripeCustomerId": z.union([z.string(), z.null()]).optional(), "stripePriceId": z.union([z.string(), z.null()]).optional(), "stripeSubscriptionStatus": z.union([z.string(), z.null()]).optional(), "updatedAt": z.string().datetime({ offset: true }), "workosOrganizationId": z.union([z.string().describe("Linked WorkOS Organization id. Populated lazily during the WorkOS importer (Phase 1) or eagerly via `provisionWorkspace` (Phase 2)."), z.null()]).optional() }), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _TenantResponseInferred = z.infer<typeof TenantResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _TenantResponseDriftCheck = _TenantResponseInferred & TenantResponse;
