// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { UpdateStripeRequest } from "../../types/endpoints/UpdateStripeRequest";

export const UpdateStripeRequestSchema = z.object({ "stripeCustomerId": z.union([z.string(), z.null()]).optional(), "stripePriceId": z.union([z.string(), z.null()]).optional(), "stripeSubscriptionStatus": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UpdateStripeRequestInferred = z.infer<typeof UpdateStripeRequestSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UpdateStripeRequestDriftCheck = _UpdateStripeRequestInferred & UpdateStripeRequest;
