// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { UpdateRunStatusRequest } from "../../types/endpoints/UpdateRunStatusRequest";

export const UpdateRunStatusRequestSchema = z.object({ "status": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UpdateRunStatusRequestInferred = z.infer<typeof UpdateRunStatusRequestSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UpdateRunStatusRequestDriftCheck = _UpdateRunStatusRequestInferred & UpdateRunStatusRequest;
