// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { UpdateAgentEndpointRequest } from "../../types/endpoints/UpdateAgentEndpointRequest";

export const UpdateAgentEndpointRequestSchema = z.object({ "authHeaderName": z.union([z.string(), z.null()]).optional(), "authType": z.union([z.string(), z.null()]).optional(), "basicUsername": z.union([z.string(), z.null()]).optional(), "endpointUrl": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UpdateAgentEndpointRequestInferred = z.infer<typeof UpdateAgentEndpointRequestSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UpdateAgentEndpointRequestDriftCheck = _UpdateAgentEndpointRequestInferred & UpdateAgentEndpointRequest;
