// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { UpsertFeatureFlagOverrideRequest } from "../../types/endpoints/UpsertFeatureFlagOverrideRequest";

export const UpsertFeatureFlagOverrideRequestSchema = z.object({ "enabled": z.boolean(), "reason": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _UpsertFeatureFlagOverrideRequestInferred = z.infer<typeof UpsertFeatureFlagOverrideRequestSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _UpsertFeatureFlagOverrideRequestDriftCheck = _UpsertFeatureFlagOverrideRequestInferred & UpsertFeatureFlagOverrideRequest;
