// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamTimelineEvent } from "../datasets/StreamTimelineEvent";

/**
 * Live envelope pushed over SSE. Three variants cover every
 * transition the viewer's cache reducer needs to handle:
 *
 *   - `snapshot`  — the server replays the most-recent window.
 *                   Used as the first frame after `(re)connect`
 *                   and on resync after a backend pause.
 *   - `appended`  — a single new event landed; cache prepends.
 *   - `heartbeat` — keep-alive so the EventSource doesn't time
 *                   out behind a load balancer.
 */
export type TimelineSubscriptionEvent = { "kind": "snapshot", events: Array<StreamTimelineEvent>, 
/**
 * ISO timestamp marking the moment the snapshot was taken.
 */
occurredAt: string, } | { "kind": "appended", event: StreamTimelineEvent, } | { "kind": "heartbeat", occurredAt: string, };
