// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamTimelineEvent } from "../datasets/StreamTimelineEvent";

/**
 * A page of timeline events. The response carries the window
 * boundaries that produced it so clients can stitch successive
 * pages back together (and so the playhead anchor on first paint
 * uses the server's clock, not the browser's).
 */
export type TimelineWindow = { 
/**
 * Events in the window, sorted ascending by `occurredAt`.
 */
events: Array<StreamTimelineEvent>, 
/**
 * Inclusive lower bound (ISO 8601). Omitted when the request
 * did not pin a `from` and the server returned the most-recent
 * `limit` events.
 */
from?: string, 
/**
 * Inclusive upper bound (ISO 8601). Defaults to "now" when the
 * caller does not specify one.
 */
to?: string, 
/**
 * `true` if events older than `from` exist that the caller can
 * page back to. Drives the timeline's "load older" affordance.
 */
hasMore: boolean, 
/**
 * Total count if the backend can supply it cheaply, otherwise
 * `None`. The dashboard does not require this; it's surfaced
 * for diagnostics only.
 */
totalCount?: number, };
