// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxDateRange } from "./SandboxDateRange";

export type EventSourceConfig = { dateRange: SandboxDateRange, sourceFilter: Array<string>, eventTypeFilter: Array<string>, };
