// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratorConfig = { sourceTypes: Array<string>, eventTypes: Array<string>, count: number, intervalMs: number, variationLevel: number, };
