// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxEdgeDto } from "./SandboxEdgeDto";
import type { SandboxNodeDto } from "./SandboxNodeDto";

export type GraphEditPreview = { nodes: Array<SandboxNodeDto>, edges: Array<SandboxEdgeDto>, };
