// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxEdgeDto } from "./SandboxEdgeDto";
import type { SandboxNodeDto } from "./SandboxNodeDto";

export type GraphEditCommand = { "type": "add_node", node: SandboxNodeDto, } | { "type": "update_node", node: SandboxNodeDto, } | { "type": "remove_node", nodeId: string, } | { "type": "add_edge", edge: SandboxEdgeDto, } | { "type": "remove_edge", edgeId: string, };
