// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxAiChatRole } from "./SandboxAiChatRole";

export type SandboxAiChatMessage = { role: SandboxAiChatRole, content: string, };
