// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventSourceConfig } from "./EventSourceConfig";
import type { FilterConfig } from "./FilterConfig";
import type { GeneratorConfig } from "./GeneratorConfig";
import type { OutputConfig } from "./OutputConfig";

export type SandboxNodeData = { "nodeType": "event-source", label: string, config: EventSourceConfig, } | { "nodeType": "filter", label: string, config: FilterConfig, } | { "nodeType": "output", label: string, config: OutputConfig, } | { "nodeType": "generator", label: string, config: GeneratorConfig, };
