// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxValidationIssue } from "./SandboxValidationIssue";

export type SandboxValidationResponse = { ok: boolean, issues: Array<SandboxValidationIssue>, };
