#!/usr/bin/env tsx
/*
 * gen-zod — read every JSON Schema produced by `cargo run -p
 * gen-contracts` and emit a matching Zod runtime validator next to
 * the ts-rs-emitted TS types, preserving folder structure.
 *
 * Inputs:  packages/chronicle/src/json-schema/<folder>/<TypeName>.json
 * Outputs: packages/chronicle/src/schemas/<folder>/<typeName>.ts  (per-type)
 *          packages/chronicle/src/schemas/<folder>/index.ts       (folder barrel)
 *          packages/chronicle/src/schemas/index.ts                (top-level barrel)
 *          packages/chronicle/src/types/<folder>/index.ts         (per-folder)
 *          packages/chronicle/src/types/index.ts                  (top-level barrel)
 *
 * Schema conventions:
 *
 *   - Schema files use kebab-case names (`dataset-snapshot.ts`) so
 *     they don't clash with the PascalCase ts-rs filenames.
 *   - Each per-schema file emits `<TypeName>Schema` plus a static
 *     drift-check assertion that fails compilation if the Zod
 *     `z.infer<typeof XSchema>` diverges from the ts-rs `X`.
 *
 * The script is intentionally idempotent — running it without changes
 * produces a no-op diff.
 */

import { jsonSchemaToZod } from "json-schema-to-zod";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageSrc = resolve(here, "..", "src");
const jsonRoot = join(packageSrc, "json-schema");
const schemasRoot = join(packageSrc, "schemas");
const typesRoot = join(packageSrc, "types");

const HEADER = `// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.`;

interface SchemaEntry {
  /** Folder relative to `json-schema/` — e.g. `"agents"`. */
  folder: string;
  /** PascalCase ts-rs type name. */
  typeName: string;
  /** kebab-cased schema file name without extension. */
  fileName: string;
  /** Parsed (post-normalised) JSON Schema. */
  rawSchema: unknown;
}

function pascalToKebab(s: string): string {
  return s
    .replace(/([a-z\d])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

function listFolders(root: string): string[] {
  return readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function readAllSchemas(): SchemaEntry[] {
  const out: SchemaEntry[] = [];
  for (const folder of listFolders(jsonRoot)) {
    const dir = join(jsonRoot, folder);
    const files = readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
    for (const fname of files) {
      const typeName = fname.replace(/\.json$/, "");
      const raw = readFileSync(join(dir, fname), "utf8");
      const parsed = JSON.parse(raw) as Record<string, unknown>;
      out.push({
        folder,
        typeName,
        fileName: pascalToKebab(typeName),
        rawSchema: normalizeNullable(parsed),
      });
    }
  }
  return out;
}

/*
 * `schemars` encodes `Option<T>` as `{ type: ["X", "null"], ...constraints }`.
 * That's a valid draft-07 shape but `json-schema-to-zod` misreads it
 * for enums (drops the `null` arm), and constraints like `enum`,
 * `format`, `minimum` aren't intended to apply to the `null` value.
 *
 * Walk the schema and rewrite `{ type: [X, "null"], ...rest }` to
 * `{ anyOf: [{ type: X, ...rest }, { type: "null" }] }`. `anyOf`
 * (vs `oneOf`) makes `json-schema-to-zod` emit a clean
 * `z.union([...])` instead of a verbose `superRefine` block.
 */
function normalizeNullable(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(normalizeNullable);
  if (node === null || typeof node !== "object") return node;
  const obj = node as Record<string, unknown>;
  const next: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    next[key] = normalizeNullable(value);
  }

  /* `schemars` emits `oneOf` for Rust enums with internally-tagged
     variants (the `nodeType` discriminator pattern). `json-schema-to-zod`
     lowers `oneOf` into a verbose `superRefine` block that doesn't
     survive `tsc --noEmit` cleanly under Zod 3. Discriminated unions
     are semantically `anyOf` whenever the discriminator makes the
     branches disjoint — which is always true for ts-rs-derived enums.
     Promote `oneOf` → `anyOf` so we get a clean `z.union([...])`. */
  if (Array.isArray(next.oneOf) && !Array.isArray(next.anyOf)) {
    next.anyOf = next.oneOf;
    delete next.oneOf;
  }

  const type = next.type;
  if (
    Array.isArray(type) &&
    type.length === 2 &&
    type.includes("null") &&
    type.some((t) => typeof t === "string" && t !== "null")
  ) {
    const concrete = type.find((t) => t !== "null") as string;
    const concreteSchema = { ...next, type: concrete };
    return { anyOf: [concreteSchema, { type: "null" }] };
  }
  return next;
}

function emitSchemaFile(entry: SchemaEntry): string {
  const { folder, typeName, rawSchema } = entry;
  const zodBody = jsonSchemaToZod(rawSchema, {
    name: `${typeName}Schema`,
    module: "esm",
    type: false,
    withJsdocs: false,
  });
  /* `json-schema-to-zod` always injects its own `import { z } from "zod"`
     when `module: "esm"`; strip it so we control the imports. */
  const cleanedBody = zodBody
    .replace(/^\s*import\s+\{\s*z\s*\}\s+from\s+["']zod["'];?\s*$/gm, "")
    /* `json-schema-to-zod` emits `z.core.$ZodIssue` (a Zod 4 internal
       type) inside the `oneOf` superRefine fallback. We pin Zod 3.x
       so consumers can `z.array(...)` etc., and Zod 3's analogue is
       `z.ZodIssue`. Functionally equivalent at runtime. */
    .replace(/z\.core\.\$ZodIssue/g, "z.ZodIssue")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return [
    HEADER,
    `import { z } from "zod";`,
    `import type { ${typeName} } from "../../types/${folder}/${typeName}";`,
    "",
    cleanedBody,
    "",
    `// Static drift guard — fails compilation if Rust + Zod diverge.`,
    `type _${typeName}Inferred = z.infer<typeof ${typeName}Schema>;`,
    `// eslint-disable-next-line @typescript-eslint/no-unused-vars`,
    `type _${typeName}DriftCheck = _${typeName}Inferred & ${typeName};`,
    "",
  ].join("\n");
}

function emitSchemaFolderBarrel(entries: readonly SchemaEntry[]): string {
  const lines = [HEADER, ""];
  for (const { typeName, fileName } of entries) {
    lines.push(`export { ${typeName}Schema } from "./${fileName}";`);
  }
  lines.push("");
  return lines.join("\n");
}

/* Same-named exports across folders (e.g. `Connection` lives in both
 * `saas/` and `connections/`) are unambiguous when imported via the
 * specific folder path but would conflict when re-exported through
 * `export * from "./<folder>"` at the top level. We avoid the
 * conflict by emitting per-name re-exports — first occurrence wins,
 * later ones get logged + force consumers onto the namespaced
 * sub-path. */
function emitTopBarrelByName(
  collectFolderNames: (folder: string) => readonly string[],
  folders: readonly string[],
  exportPrefix: string,
  kind: "schemas" | "types",
): string {
  const lines = [HEADER, ""];
  const seen = new Map<string, string>();
  const collisions: { name: string; first: string; second: string }[] = [];

  for (const folder of folders) {
    for (const symbol of collectFolderNames(folder)) {
      const exportName = `${symbol}${exportPrefix}`;
      const earlier = seen.get(exportName);
      if (earlier !== undefined) {
        collisions.push({ name: exportName, first: earlier, second: folder });
        continue;
      }
      seen.set(exportName, folder);
      const importer =
        kind === "schemas"
          ? `export { ${exportName} } from "./${folder}";`
          : `export type { ${exportName} } from "./${folder}";`;
      lines.push(importer);
    }
  }

  if (collisions.length > 0 && typeof console !== "undefined") {
    for (const { name, first, second } of collisions) {
      console.warn(
        `[gen-zod] ${kind} collision: "${name}" exists in "${first}" and "${second}"; top-level barrel exports the "${first}" one. Import from "chronicle/${kind}/${second}" for the other.`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

function emitTypesFolderBarrel(typeNames: readonly string[]): string {
  const lines = [
    "// Auto-generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.",
    "// Mirrors the .ts files emitted by `cargo run -p gen-contracts` in this folder.",
    "",
  ];
  for (const name of typeNames) {
    lines.push(`export type { ${name} } from "./${name}";`);
  }
  lines.push("");
  return lines.join("\n");
}

/* Top-level barrel for `types/`. See `emitTopBarrelByName` above. */

function main() {
  mkdirSync(schemasRoot, { recursive: true });

  const entries = readAllSchemas();

  /* Group entries by folder so we can emit per-folder barrels. */
  const byFolder = new Map<string, SchemaEntry[]>();
  for (const entry of entries) {
    const list = byFolder.get(entry.folder) ?? [];
    list.push(entry);
    byFolder.set(entry.folder, list);
  }

  /* Write per-type schema files + per-folder barrels. */
  for (const [folder, list] of byFolder) {
    const dir = join(schemasRoot, folder);
    mkdirSync(dir, { recursive: true });
    for (const entry of list) {
      writeFileSync(
        join(dir, `${entry.fileName}.ts`),
        emitSchemaFile(entry),
      );
    }
    writeFileSync(join(dir, "index.ts"), emitSchemaFolderBarrel(list));
  }

  const folders = [...byFolder.keys()].sort();
  writeFileSync(
    join(schemasRoot, "index.ts"),
    emitTopBarrelByName(
      (folder) =>
        (byFolder.get(folder) ?? []).map((entry) => entry.typeName),
      folders,
      "Schema",
      "schemas",
    ),
  );

  /* Also (re)write `chronicle/src/types/<folder>/index.ts` and the
     top-level `chronicle/src/types/index.ts` barrel so a new Rust
     shape doesn't require a hand-edit on the TS side. */
  const typesByFolder = new Map<string, string[]>();
  for (const folder of listFolders(typesRoot)) {
    const dir = join(typesRoot, folder);
    const generatedFiles = readdirSync(dir)
      .filter((f) => f.endsWith(".ts") && f !== "index.ts")
      .map((f) => f.replace(/\.ts$/, ""))
      .sort();
    typesByFolder.set(folder, generatedFiles);
    writeFileSync(
      join(dir, "index.ts"),
      emitTypesFolderBarrel(generatedFiles),
    );
  }
  writeFileSync(
    join(typesRoot, "index.ts"),
    emitTopBarrelByName(
      (folder) => typesByFolder.get(folder) ?? [],
      [...typesByFolder.keys()].sort(),
      "",
      "types",
    ),
  );

  // eslint-disable-next-line no-console
  console.log(
    `[gen-zod] wrote ${entries.length} schema(s) across ${folders.length} folder(s) under ${schemasRoot}`,
  );
}

main();
