// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionEventTypeSub } from "../../types/connections/ConnectionEventTypeSub";

export const ConnectionEventTypeSubSchema = z.object({ "defaultOn": z.union([z.boolean().describe("Whether this row was on by default at install time."), z.null()]).optional(), "enabled": z.boolean(), "id": z.string(), "object": z.union([z.string().describe("Optional Stripe-style object hint (`charge`, `customer`, …)."), z.null()]).optional() }).describe("Per-event-type toggle row (e.g. Stripe `charge.succeeded`). Renders inside the drawer's Event-types tab.")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionEventTypeSubInferred = z.infer<typeof ConnectionEventTypeSubSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionEventTypeSubDriftCheck = _ConnectionEventTypeSubInferred & ConnectionEventTypeSub;
