// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionDelivery } from "../../types/connections/ConnectionDelivery";

export const ConnectionDeliverySchema = z.object({ "method": z.union([z.string(), z.null()]).optional(), "preview": z.string(), "status": z.number().int().gte(0).describe("HTTP status; `< 200` or `>= 300` tints the row red."), "ts": z.string().describe("Wall-clock time string the activity tab renders directly (e.g. `13:02:14`). NOT a full ISO timestamp — the row's purpose is \"what just happened in the last few minutes\".") })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionDeliveryInferred = z.infer<typeof ConnectionDeliverySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionDeliveryDriftCheck = _ConnectionDeliveryInferred & ConnectionDelivery;
