// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectorErrorKind } from "../../types/connections/ConnectorErrorKind";

export const ConnectorErrorKindSchema = z.enum(["auth","signature","rate-limit","unknown"]).describe("Classifies a `health == \"error\"` failure for the connector state-error modal. Mirrors the TS `ConnectorErrorKind` union.")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectorErrorKindInferred = z.infer<typeof ConnectorErrorKindSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectorErrorKindDriftCheck = _ConnectorErrorKindInferred & ConnectorErrorKind;
