// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionBackfillStatus } from "../../types/connections/ConnectionBackfillStatus";

export const ConnectionBackfillStatusSchema = z.enum(["running","done","failed"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionBackfillStatusInferred = z.infer<typeof ConnectionBackfillStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionBackfillStatusDriftCheck = _ConnectionBackfillStatusInferred & ConnectionBackfillStatus;
