// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionHealth } from "../../types/connections/ConnectionHealth";

export const ConnectionHealthSchema = z.enum(["live","paused","error","expired","testing","disconnected"]).describe("Operational state of a live connection. Drives the `ConnectionHealthBadge` colour, the row's right-side hint, and whether the action menu shows \"Reauth\" / \"Retry\" / \"Resume\".")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionHealthInferred = z.infer<typeof ConnectionHealthSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionHealthDriftCheck = _ConnectionHealthInferred & ConnectionHealth;
