// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionTestStatus } from "../../types/connections/ConnectionTestStatus";

export const ConnectionTestStatusSchema = z.enum(["ok","fail","pending"]).describe("Outcome of the last `Test connection` run. `Pending` means the test is in flight; the row's button stays in a wait state.")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionTestStatusInferred = z.infer<typeof ConnectionTestStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionTestStatusDriftCheck = _ConnectionTestStatusInferred & ConnectionTestStatus;
