// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { ConnectionBackfillRecord } from "../../types/connections/ConnectionBackfillRecord";

export const ConnectionBackfillRecordSchema = z.object({ "entities": z.array(z.string()).describe("Subset of entity ids the user picked (e.g. `conversations`, `contacts`)."), "estEvents": z.number().int().gte(0).describe("Estimator output at submit time."), "finishedAt": z.union([z.string().datetime({ offset: true }).describe("Absent while still running."), z.null()]).optional(), "id": z.string(), "startedAt": z.string().datetime({ offset: true }), "status": z.enum(["running","done","failed"]), "windowDays": z.number().int().gte(0).describe("Lookback window in days.") }).describe("Persisted backfill log row. The currently-running shape lives in the onboarding store on the TS side; this is the historical record returned by the dashboard.")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _ConnectionBackfillRecordInferred = z.infer<typeof ConnectionBackfillRecordSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _ConnectionBackfillRecordDriftCheck = _ConnectionBackfillRecordInferred & ConnectionBackfillRecord;
