import type {
  EnvironmentToolTemplate,
  SandboxEnvironment,
} from "./types";

export const ENVIRONMENT_TOOL_CATALOG: readonly EnvironmentToolTemplate[] = [
  {
    id: "tool_stripe_mcp",
    name: "stripe-mcp",
    source: "stripe",
    kind: "mcp",
    mode: "sandboxed-writes",
    category: "Billing",
    capabilities: [
      "customers.read",
      "invoices.read",
      "charges.refund",
      "subscriptions.update",
    ],
    description:
      "Stripe MCP server with sandboxed write replay for refunds, invoices, and customers.",
  },
  {
    id: "tool_stripe_cli",
    name: "stripe-cli",
    source: "stripe",
    kind: "cli",
    mode: "sandboxed-writes",
    category: "Billing",
    capabilities: ["events.tail", "customers.read", "charges.create"],
    description:
      "Stripe CLI inside the sandbox runtime for event tailing and refund testing.",
  },
  {
    id: "tool_slack_mcp",
    name: "slack-mcp",
    source: "slack",
    kind: "mcp",
    mode: "sandboxed-writes",
    category: "Messaging",
    capabilities: ["channels.read", "chat.write", "users.lookup"],
    description:
      "MCP server for Slack channel reads, user lookups, and safe message posts.",
  },
  {
    id: "tool_slack_cli",
    name: "slack-cli",
    source: "slack",
    kind: "cli",
    mode: "sandboxed-writes",
    category: "Messaging",
    capabilities: ["channels.read", "chat.write"],
    description:
      "Slack CLI mounted in the agent runtime for safe channel writes.",
  },
  {
    id: "tool_gmail_cli",
    name: "email-cli",
    source: "gmail",
    kind: "cli",
    mode: "mocked",
    category: "Messaging",
    capabilities: ["inbox.read", "draft.write", "send.mock"],
    description:
      "Mocked Gmail CLI seeded with invites, follow-ups, and SSO messages.",
  },
  {
    id: "tool_hubspot_mcp",
    name: "hubspot-mcp",
    source: "hubspot",
    kind: "mcp",
    mode: "sandboxed-writes",
    category: "CRM",
    capabilities: ["contacts.read", "deals.write", "companies.read"],
    description:
      "HubSpot MCP server with seeded contacts, deals, and pipeline state.",
  },
  {
    id: "tool_salesforce_mcp",
    name: "salesforce-mcp",
    source: "salesforce",
    kind: "mcp",
    mode: "sandboxed-writes",
    category: "CRM",
    capabilities: ["opportunity.read", "account.read", "contact.write"],
    description:
      "Salesforce MCP server with replay-backed opportunity and account state.",
  },
  {
    id: "tool_postgres_db",
    name: "support-db",
    source: "postgres",
    kind: "database",
    mode: "replay-backed",
    category: "Database",
    capabilities: ["tickets.read", "customers.read", "notes.write"],
    description:
      "Replay-backed Postgres database seeded with customer, ticket, and policy rows.",
  },
  {
    id: "tool_postgres_audit",
    name: "audit-db",
    source: "postgres",
    kind: "database",
    mode: "replay-backed",
    category: "Database",
    capabilities: ["audit.read", "cases.read", "decisions.write"],
    description:
      "Replay-backed audit log database with decision records and history.",
  },
  {
    id: "tool_filesystem",
    name: "workspace-files",
    source: "filesystem",
    kind: "filesystem",
    mode: "read-only",
    category: "Filesystem",
    capabilities: ["docs.read", "templates.read", "policy.read"],
    description:
      "Mounted files for policies, templates, runbooks, and historical examples.",
  },
  {
    id: "tool_http_api",
    name: "http-api",
    source: "api",
    kind: "api",
    mode: "mocked",
    category: "Custom",
    capabilities: ["http.get", "http.post"],
    description:
      "Generic HTTP API shim for arbitrary endpoints, mocked to a recorded fixture.",
  },
  {
    id: "tool_webhook_api",
    name: "webhook-api",
    source: "webhook",
    kind: "api",
    mode: "replay-backed",
    category: "Custom",
    capabilities: ["webhook.send", "webhook.replay"],
    description:
      "Outbound webhook surface backed by recorded production deliveries.",
  },
];

const ANCHOR = Date.parse("2026-05-04T16:30:00.000Z");

function iso(minutesAgo: number) {
  return new Date(ANCHOR - minutesAgo * 60_000).toISOString();
}

const refundScenarioSet = {
  id: "scenario_refunds_v2",
  name: "Refund escalations v2",
  description:
    "Billing, support, and policy traces where agents must inspect Stripe, Slack, and customer history before refunding.",
  count: 1248,
  coverage: ["refunds", "dunning", "policy exceptions", "manager handoff"],
  recommendedTools: ["stripe-mcp", "slack-cli", "support-db"],
};

const onboardingScenarioSet = {
  id: "scenario_onboarding",
  name: "Enterprise onboarding",
  description:
    "Workspace provisioning flows with email invites, Slack follow-ups, files, and account setup state.",
  count: 864,
  coverage: ["invites", "SSO", "workspace setup", "missing files"],
  recommendedTools: ["slack-mcp", "email-cli", "filesystem"],
};

const trustScenarioSet = {
  id: "scenario_trust_safety",
  name: "Trust and safety queue",
  description:
    "Policy review scenarios with user reports, message context, audit logs, and escalation boundaries.",
  count: 612,
  coverage: ["abuse reports", "policy checks", "audit log", "human review"],
  recommendedTools: ["slack-cli", "audit-db", "filesystem"],
};

export const environmentsSeed: readonly SandboxEnvironment[] = [
  {
    id: "env_acme_refunds",
    name: "Acme Support Sandbox",
    company: "Acme Retail",
    description:
      "Safe company replica for refund, dunning, and support escalation agents.",
    owner: "support-platform",
    status: "ready",
    updatedAt: iso(12),
    eventsPerMin: 28,
    activeAgents: 4,
    tags: ["refunds", "stripe", "support"],
    resources: { vCpu: 2, memoryGib: 4, diskGib: 20 },
    currentSnapshot: {
      id: "snap_refunds_2026_05_04",
      name: "Refund escalation v2 snapshot",
      sourceDataset: "refund-escalations-v2",
      seededAt: iso(24),
      scenarios: 1248,
      entities: 389,
      records: 18320,
      files: 142,
      traces: 412,
      traceSeeds: [
        {
          id: "tr_8a3f12",
          title: "Refund INV-2049 with policy override",
          sources: ["stripe", "slack", "postgres"],
          events: 48,
          records: 24,
          entities: 3,
          files: 2,
        },
        {
          id: "tr_19cd44",
          title: "Manager escalation on $9.4k refund",
          sources: ["stripe", "postgres"],
          events: 31,
          records: 18,
          entities: 2,
          files: 1,
        },
        {
          id: "tr_44b187",
          title: "Subscription dunning sweep",
          sources: ["stripe", "postgres", "slack"],
          events: 64,
          records: 42,
          entities: 6,
          files: 0,
        },
        {
          id: "tr_71fe09",
          title: "Customer churn risk: Acme Co",
          sources: ["postgres", "slack"],
          events: 22,
          records: 14,
          entities: 1,
          files: 1,
        },
        {
          id: "tr_2c0431",
          title: "Policy file change ripple",
          sources: ["filesystem", "slack"],
          events: 14,
          records: 6,
          entities: 0,
          files: 4,
        },
        {
          id: "tr_5fa370",
          title: "Receipt resend batch",
          sources: ["stripe"],
          events: 9,
          records: 9,
          entities: 0,
          files: 0,
        },
      ],
    },
    scenarioSets: [refundScenarioSet, onboardingScenarioSet],
    tools: [
      {
        id: "stripe-mcp",
        name: "stripe-mcp",
        kind: "mcp",
        source: "stripe",
        mode: "sandboxed-writes",
        status: "available",
        latencyMs: 18,
        enabled: true,
        capabilities: [
          "customers.read",
          "invoices.read",
          "charges.refund",
          "subscriptions.update",
        ],
        description:
          "MCP server seeded from the Stripe connection with sandboxed write replay.",
      },
      {
        id: "slack-cli",
        name: "slack-cli",
        kind: "cli",
        source: "slack",
        mode: "sandboxed-writes",
        status: "available",
        latencyMs: 42,
        enabled: true,
        capabilities: ["channels.read", "chat.write", "users.read"],
        description:
          "CLI available inside the agent runtime for team context and safe message posting.",
      },
      {
        id: "support-db",
        name: "support-db",
        kind: "database",
        source: "postgres",
        mode: "replay-backed",
        status: "available",
        latencyMs: 9,
        enabled: true,
        capabilities: ["tickets.read", "customers.read", "notes.write"],
        description:
          "Replay-backed support database seeded with customer, ticket, and policy rows.",
      },
      {
        id: "policy-files",
        name: "policy-files",
        kind: "filesystem",
        source: "filesystem",
        mode: "read-only",
        status: "available",
        latencyMs: 4,
        enabled: true,
        capabilities: ["refund-policy.read", "templates.read"],
        description:
          "Mounted files for policies, macros, and historical support examples.",
      },
    ],
    failures: [
      {
        id: "failure_slack_timeout",
        name: "Slack post timeout",
        target: "slack-cli",
        description:
          "chat.write hangs for 12 seconds before returning a retryable timeout.",
        active: false,
        severity: "medium",
      },
      {
        id: "failure_stripe_idempotency",
        name: "Stripe idempotency conflict",
        target: "stripe-mcp",
        description:
          "Refund creation returns an idempotency conflict for duplicate attempts.",
        active: false,
        severity: "high",
      },
      {
        id: "failure_db_readonly",
        name: "Support DB read-only",
        target: "support-db",
        description: "Ticket note writes fail while reads continue normally.",
        active: false,
        severity: "low",
      },
    ],
    agentIdentities: [
      {
        id: "agent_refund_ops",
        label: "Refund Ops Agent",
        principal: "refund-agent@acme-sandbox",
        scopes: ["stripe.refunds", "slack.post", "tickets.write"],
      },
      {
        id: "agent_manager_review",
        label: "Manager Reviewer",
        principal: "billing-reviewer@acme-sandbox",
        scopes: ["tickets.read", "policy.read"],
      },
    ],
    activity: [
      {
        id: "act_1",
        kind: "agent",
        title: "Refund Ops Agent completed scenario batch",
        detail: "84 pass, 3 retryable tool failures, 1 policy escalation.",
        at: iso(5),
        actor: "backtest-runner",
      },
      {
        id: "act_2",
        kind: "tool",
        title: "stripe-mcp handled refund.create",
        detail: "Sandboxed write recorded against replay account cus_9F3A.",
        at: iso(7),
        actor: "refund-agent@acme-sandbox",
      },
      {
        id: "act_3",
        kind: "seed",
        title: "Seeded Refund escalations v2",
        detail: "1248 scenarios, 389 entities, 4 tool runtimes.",
        at: iso(24),
        actor: "sara",
      },
    ],
  },
  {
    id: "env_northstar_onboarding",
    name: "Northstar Onboarding Lab",
    company: "Northstar Health",
    description:
      "Agent runtime for workspace setup, file lookups, invites, and onboarding support.",
    owner: "enterprise-success",
    status: "degraded",
    updatedAt: iso(36),
    eventsPerMin: 16,
    activeAgents: 2,
    tags: ["onboarding", "slack", "email"],
    resources: { vCpu: 1, memoryGib: 2, diskGib: 10 },
    currentSnapshot: {
      id: "snap_onboarding_2026_05_04",
      name: "Enterprise onboarding snapshot",
      sourceDataset: "enterprise-onboarding-q2",
      seededAt: iso(54),
      scenarios: 864,
      entities: 211,
      records: 9400,
      files: 88,
      traces: 268,
      traceSeeds: [
        {
          id: "tr_a9c116",
          title: "SSO setup for ENT-44",
          sources: ["slack", "gmail"],
          events: 28,
          records: 12,
          entities: 2,
          files: 1,
        },
        {
          id: "tr_b8d3f2",
          title: "Missing implementation plan flagged",
          sources: ["filesystem", "slack"],
          events: 11,
          records: 4,
          entities: 1,
          files: 3,
        },
        {
          id: "tr_c0f783",
          title: "Invite resend batch (cohort 7)",
          sources: ["gmail", "slack"],
          events: 19,
          records: 14,
          entities: 5,
          files: 0,
        },
        {
          id: "tr_d4e2a5",
          title: "Workspace provisioning - Vortex",
          sources: ["slack", "gmail", "filesystem"],
          events: 36,
          records: 22,
          entities: 4,
          files: 2,
        },
        {
          id: "tr_e5a103",
          title: "Onboarding handbook lookup",
          sources: ["filesystem"],
          events: 7,
          records: 1,
          entities: 0,
          files: 2,
        },
      ],
    },
    scenarioSets: [onboardingScenarioSet, trustScenarioSet],
    tools: [
      {
        id: "slack-mcp",
        name: "slack-mcp",
        kind: "mcp",
        source: "slack",
        mode: "sandboxed-writes",
        status: "faulted",
        latencyMs: 2100,
        enabled: true,
        capabilities: ["channels.read", "chat.write", "users.lookup"],
        description:
          "MCP surface for channel history, onboarding reminders, and safe posts.",
      },
      {
        id: "email-cli",
        name: "email-cli",
        kind: "cli",
        source: "gmail",
        mode: "mocked",
        status: "available",
        latencyMs: 33,
        enabled: true,
        capabilities: ["inbox.read", "draft.write", "send.mock"],
        description:
          "Command-line mail surface seeded with invite, follow-up, and SSO messages.",
      },
      {
        id: "filesystem",
        name: "workspace-files",
        kind: "filesystem",
        source: "filesystem",
        mode: "read-only",
        status: "available",
        latencyMs: 6,
        enabled: true,
        capabilities: ["handbook.read", "implementation-plan.read"],
        description:
          "Mounted implementation docs, onboarding checklists, and contract files.",
      },
    ],
    failures: [
      {
        id: "failure_slack_scope",
        name: "Slack scope missing",
        target: "slack-mcp",
        description:
          "users.lookup returns missing_scope for one enterprise workspace.",
        active: true,
        severity: "medium",
      },
      {
        id: "failure_missing_file",
        name: "Missing implementation plan",
        target: "filesystem",
        description: "A linked implementation plan path resolves to not found.",
        active: false,
        severity: "low",
      },
    ],
    agentIdentities: [
      {
        id: "agent_onboarding",
        label: "Onboarding Agent",
        principal: "onboarding-agent@northstar-sandbox",
        scopes: ["slack.post", "email.draft", "files.read"],
      },
    ],
    activity: [
      {
        id: "act_4",
        kind: "failure",
        title: "Injected Slack scope missing",
        detail: "users.lookup is returning missing_scope for ACME-ENT-44.",
        at: iso(29),
        actor: "ernesto",
      },
      {
        id: "act_5",
        kind: "tool",
        title: "email-cli drafted onboarding follow-up",
        detail: "Draft held in sandbox, no external email sent.",
        at: iso(35),
        actor: "onboarding-agent@northstar-sandbox",
      },
      {
        id: "act_6",
        kind: "seed",
        title: "Seeded Enterprise onboarding",
        detail: "864 scenarios and 3 tool runtimes installed.",
        at: iso(54),
        actor: "alex",
      },
    ],
  },
  {
    id: "env_vector_trust",
    name: "Vector Trust Sandbox",
    company: "Vector Social",
    description:
      "Trust and safety sandbox with audit log, Slack review queues, and policy files.",
    owner: "trust-and-safety",
    status: "needs-reset",
    updatedAt: iso(180),
    eventsPerMin: 4,
    activeAgents: 0,
    tags: ["policy", "audit", "review"],
    resources: { vCpu: 1, memoryGib: 2, diskGib: 8 },
    currentSnapshot: {
      id: "snap_trust_2026_05_04",
      name: "Trust and safety queue snapshot",
      sourceDataset: "policy-review-queue",
      seededAt: iso(280),
      scenarios: 612,
      entities: 144,
      records: 5210,
      files: 47,
      traces: 133,
      traceSeeds: [
        {
          id: "tr_p3kf28",
          title: "Policy review - report #4421",
          sources: ["postgres", "filesystem"],
          events: 18,
          records: 12,
          entities: 2,
          files: 1,
        },
        {
          id: "tr_q5wn14",
          title: "Audit trail audit",
          sources: ["postgres"],
          events: 12,
          records: 12,
          entities: 1,
          files: 0,
        },
        {
          id: "tr_r8mh92",
          title: "Appeal review case 1023",
          sources: ["postgres", "slack"],
          events: 25,
          records: 16,
          entities: 3,
          files: 1,
        },
        {
          id: "tr_s2vt07",
          title: "Policy version drift report",
          sources: ["filesystem"],
          events: 6,
          records: 0,
          entities: 0,
          files: 4,
        },
      ],
    },
    scenarioSets: [trustScenarioSet, refundScenarioSet],
    tools: [
      {
        id: "audit-db",
        name: "audit-db",
        kind: "database",
        source: "postgres",
        mode: "replay-backed",
        status: "available",
        latencyMs: 14,
        enabled: true,
        capabilities: ["audit.read", "cases.read", "decisions.write"],
        description:
          "Replay-backed review queue with audit trails and decision records.",
      },
      {
        id: "slack-cli",
        name: "slack-cli",
        kind: "cli",
        source: "slack",
        mode: "read-only",
        status: "disabled",
        latencyMs: 0,
        enabled: false,
        capabilities: ["channels.read", "users.read"],
        description:
          "Read-only Slack CLI disabled until this environment is reset.",
      },
      {
        id: "policy-files",
        name: "policy-files",
        kind: "filesystem",
        source: "filesystem",
        mode: "read-only",
        status: "available",
        latencyMs: 5,
        enabled: true,
        capabilities: ["policy.read", "appeals-template.read"],
        description:
          "Mounted policy docs, decision templates, and escalation rubrics.",
      },
    ],
    failures: [
      {
        id: "failure_policy_drift",
        name: "Policy file drift",
        target: "policy-files",
        description: "One scenario references a retired policy version.",
        active: true,
        severity: "high",
      },
    ],
    agentIdentities: [
      {
        id: "agent_policy_review",
        label: "Policy Review Agent",
        principal: "policy-agent@vector-sandbox",
        scopes: ["audit.read", "cases.write", "policy.read"],
      },
    ],
    activity: [
      {
        id: "act_7",
        kind: "failure",
        title: "Policy drift detected",
        detail: "14 scenarios cite policy/refunds-2025.md after latest seed.",
        at: iso(160),
        actor: "validator",
      },
      {
        id: "act_8",
        kind: "agent",
        title: "Policy Review Agent paused",
        detail: "Environment needs reset before the next run.",
        at: iso(176),
        actor: "backtest-runner",
      },
    ],
  },
];
