// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionHealth } from "./ConnectionHealth";
import type { ConnectionTestStatus } from "./ConnectionTestStatus";
import type { ConnectorErrorKind } from "./ConnectorErrorKind";

export type Connection = { 
/**
 * Stable id (e.g. `conn_3PJz4Z…`).
 */
id: string, 
/**
 * Catalog source id (joins with the design-system `SOURCES`
 * catalog). Free-form string so adding a new vendor doesn't
 * require bumping a Rust enum.
 */
source: string, 
/**
 * Workspace alias for the connection. Defaults to
 * `source.name` at install time.
 */
name: string, health: ConnectionHealth, 
/**
 * ISO timestamp the connection was first authorized.
 */
connectedAt: string, 
/**
 * ISO timestamp of the most recent event observed.
 */
lastEventAt: string, 
/**
 * Rolling 24-hour event count.
 */
eventsLast24h: number, 
/**
 * Granted scope ids — joins with the per-vendor scope catalog.
 */
scopes: Array<string>, 
/**
 * Optional point-of-contact email for the install.
 */
ownerEmail?: string, 
/**
 * 24-bucket sparkline values (events/hour).
 */
spark?: Array<number>, 
/**
 * Populated when `health == "error"`; classifies the failure.
 */
errorKind?: ConnectorErrorKind, 
/**
 * Populated when `health == "expired"`; ISO of token expiry.
 */
expiresAt?: string, 
/**
 * Populated when `health == "error"`; raw payload string for
 * the inspector.
 */
errorPayload?: string, 
/**
 * ISO timestamp of the last manual "Test connection" run.
 * Older connections that pre-date the field render a `—` cell.
 */
lastTestedAt?: string, 
/**
 * Outcome of the last `Test connection` run.
 */
lastTestStatus?: ConnectionTestStatus, 
/**
 * Previous-period (24h) event count, used to compute a trend
 * delta on the card view ("+12% vs prev 24h").
 */
prevEventsLast24h?: number, };
