// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a `health == "error"` failure for the connector
 * state-error modal. Mirrors the TS `ConnectorErrorKind` union.
 */
export type ConnectorErrorKind = "auth" | "signature" | "rate-limit" | "unknown";
