// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of the last `Test connection` run. `Pending` means the
 * test is in flight; the row's button stays in a wait state.
 */
export type ConnectionTestStatus = "ok" | "fail" | "pending";
