// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operational state of a live connection. Drives the
 * `ConnectionHealthBadge` colour, the row's right-side hint, and
 * whether the action menu shows "Reauth" / "Retry" / "Resume".
 */
export type ConnectionHealth = "live" | "paused" | "error" | "expired" | "testing" | "disconnected";
