// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-event-type toggle row (e.g. Stripe `charge.succeeded`).
 * Renders inside the drawer's Event-types tab.
 */
export type ConnectionEventTypeSub = { id: string, 
/**
 * Optional Stripe-style object hint (`charge`, `customer`, …).
 */
object?: string, enabled: boolean, 
/**
 * Whether this row was on by default at install time.
 */
defaultOn?: boolean, };
