// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionBackfillStatus } from "./ConnectionBackfillStatus";

/**
 * Persisted backfill log row. The currently-running shape lives
 * in the onboarding store on the TS side; this is the historical
 * record returned by the dashboard.
 */
export type ConnectionBackfillRecord = { id: string, 
/**
 * Lookback window in days.
 */
windowDays: number, 
/**
 * Subset of entity ids the user picked (e.g. `conversations`,
 * `contacts`).
 */
entities: Array<string>, 
/**
 * Estimator output at submit time.
 */
estEvents: number, startedAt: string, 
/**
 * Absent while still running.
 */
finishedAt?: string, status: ConnectionBackfillStatus, };
