// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionDelivery = { 
/**
 * Wall-clock time string the activity tab renders directly
 * (e.g. `13:02:14`). NOT a full ISO timestamp — the row's
 * purpose is "what just happened in the last few minutes".
 */
ts: string, method?: string, preview: string, 
/**
 * HTTP status; `< 200` or `>= 300` tints the row red.
 */
status: number, };
