// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phases inside the Configure stage. The configure flow is a
 * directional pipeline: pick → coverage → environment → versions →
 * launch.
 */
export type BacktestConfigurePhase = "pick" | "coverage" | "environment" | "versions";
