// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSummary } from "../agents/AgentSummary";
import type { BacktestEnvironmentRef } from "./BacktestEnvironmentRef";
import type { Dataset } from "../datasets/Dataset";
import type { DatasetSnapshot } from "../datasets/DatasetSnapshot";

/**
 * Returned by `GET /api/platform/backtests/availability`. Matches the
 * frontend's `BacktestsAvailability`. Datasets, environments, and
 * agents come from their respective domain crates' types — the IDs in
 * these slices are what the recipe references.
 */
export type BacktestsAvailability = { datasets: Array<Dataset>, datasetSnapshots: { [key in string]?: DatasetSnapshot }, 
/**
 * Environment row identities + status. Detailed snapshot lives
 * behind `GET /api/platform/environments/:id`.
 */
environments: Array<BacktestEnvironmentRef>, agents: Array<AgentSummary>, };
