// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestJobMode } from "./BacktestJobMode";
import type { BacktestRunStatus } from "./BacktestRunStatus";

/**
 * Compact projection of a backtest run rendered on the list view.
 * Combines the recipe identity (mode, environment, agents, dataset)
 * with run lifecycle metadata (status, verdict, divergences).
 */
export type BacktestRunSummary = { id: string, 
/**
 * Display name of the run (matches `BacktestRecipe.name`).
 */
name: string, mode: BacktestJobMode, status: BacktestRunStatus, 
/**
 * ISO timestamp of the most recent state change — drives "ago".
 */
updatedAt: string, scheduledFor?: string, 
/**
 * Display label for the dataset / production window seed.
 */
datasetLabel: string, environmentLabel?: string, 
/**
 * Agent ids participating in the run; the first is the baseline.
 */
agentIds: Array<string>, 
/**
 * Total cases × agents; null while still drafting.
 */
totalRuns?: number, verdict?: string, hue?: string, 
/**
 * Divergences observed (only set when status is `done` / `failed`).
 */
divergences?: number, owner?: string, };
