// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row projection of `"BacktestArtifact"`.
 */
export type BacktestArtifactKind = "agent-log" | "verifier-log" | "trajectory" | "screenshot" | "reward-json" | "reward-txt" | "tar" | "other";
