// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestDivergenceDelta } from "./BacktestDivergenceDelta";
import type { BacktestDivergenceSeverity } from "./BacktestDivergenceSeverity";
import type { BacktestDivergenceSide } from "./BacktestDivergenceSide";

export type BacktestDivergence = { id: string, prompt: string, cluster: string, hue: string, baseline: BacktestDivergenceSide, candidate: BacktestDivergenceSide, delta: BacktestDivergenceDelta, severity: BacktestDivergenceSeverity, 
/**
 * Grader id (joins with `BacktestGrader.id`).
 */
grader: string, note: string, };
