// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestAgent } from "./BacktestAgent";

export type BacktestCandidateProgress = { agent: BacktestAgent, isBaseline: boolean, pct: number, done: number, total: number, passPct: number, divergencePct?: number, errorPct: number, avgDuration: string, spent: string, };
