// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestOutcome } from "./BacktestOutcome";

export type BacktestDivergenceSide = { label?: string, outcome: BacktestOutcome, turns: number, latency: string, verdict: string, };
