// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestGraderKind } from "./BacktestGraderKind";
import type { BacktestGraderPreviewRow } from "./BacktestGraderPreviewRow";
import type { BacktestGraderWeight } from "./BacktestGraderWeight";

export type BacktestProposedGrader = { id: string, label: string, kind: BacktestGraderKind, weight: BacktestGraderWeight, 
/**
 * 0..1 — rendered as a percentage in the proposed card.
 */
confidence: number, evidence: string, preview: Array<BacktestGraderPreviewRow>, };
