// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestDivergence } from "./BacktestDivergence";
import type { BacktestMetric } from "./BacktestMetric";
import type { BacktestRecipe } from "./BacktestRecipe";
import type { BacktestStage } from "./BacktestStage";

/**
 * Returned by `GET /api/platform/backtests/scene`. `null` (handled at
 * the route level) means "no pre-baked scene; fall back to list view".
 */
export type BacktestsScene = { initialStage?: BacktestStage, initialRecipe?: BacktestRecipe, divergences?: Array<BacktestDivergence>, metrics?: Array<BacktestMetric>, };
