// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestAgentRole } from "./BacktestAgentRole";

export type BacktestAgent = { id: string, label: string, 
/**
 * Tag rendered next to the label, e.g. "current production".
 */
notes: string, 
/**
 * CSS color token / hex. Used by `CandidateHueDot`.
 */
hue: string, 
/**
 * Defaults to `candidate`; the Results table treats the first
 * baseline as the reference column.
 */
role?: BacktestAgentRole, };
