// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestJobMode } from "./BacktestJobMode";
import type { JobStatus } from "./JobStatus";
import type { RetryConfig } from "./RetryConfig";
import type { SandboxDriver } from "./SandboxDriver";

/**
 * Row projection of `"BacktestJob"`.
 */
export type BacktestJobRecord = { id: string, tenantId: string, name: string, mode: BacktestJobMode, 
/**
 * Full BacktestRecipe blob persisted at submit time.
 */
recipe: Record<string, unknown>, status: JobStatus, verdict?: string, nConcurrent: number, sandboxDriver: SandboxDriver, retryConfig?: RetryConfig, createdBy?: string, scheduledFor?: string, createdAt: string, startedAt?: string, finishedAt?: string, totalTrials?: number, completedTrials: number, failedTrials: number, exceptionKind?: string, updatedAt: string, };
