// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestAgent } from "./BacktestAgent";
import type { BacktestData } from "./BacktestData";
import type { BacktestEnvironmentRef } from "./BacktestEnvironmentRef";
import type { BacktestGrader } from "./BacktestGrader";
import type { BacktestJobMode } from "./BacktestJobMode";

export type BacktestRecipe = { mode: BacktestJobMode, 
/**
 * 1..N agents under test. The first is treated as the comparison
 * baseline by `BacktestResults`.
 */
agents: Array<BacktestAgent>, data: BacktestData, graders: Array<BacktestGrader>, 
/**
 * Optional environment the run targets. Pipeline step 03 sets
 * this; consumers without an environment fall back to the default
 * ephemeral sandbox.
 */
environment?: BacktestEnvironmentRef, 
/**
 * Free-text run name shown in the recipe header + top nav.
 */
name: string, 
/**
 * Optional pinned trace seed; used by the Replay preset to
 * reproduce a single trace as the focal point of the run.
 */
seed?: string, };
