// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestJobIcon } from "./BacktestJobIcon";
import type { BacktestJobMode } from "./BacktestJobMode";
import type { BacktestRecipe } from "./BacktestRecipe";

export type BacktestJobPreset = { id: BacktestJobMode, title: string, sub: string, why: string, icon: BacktestJobIcon, 
/**
 * CSS color (token or hex) painted on the card glyph.
 */
hue: string, recipe: BacktestRecipe, };
