// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grader weight bucket — `low | med | high` matches the segmented
 * control in the GraderBuilder tray.
 */
export type BacktestGraderWeight = "low" | "med" | "high";
