// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestLiveCaseStatus } from "./BacktestLiveCaseStatus";

export type BacktestLiveCase = { id: string, cluster: string, prompt: string, ts: string, status: BacktestLiveCaseStatus, durationSec: number, agentId: string, };
