// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestArtifactKind } from "./BacktestArtifactKind";

export type BacktestArtifactRecord = { id: string, trialId: string, kind: BacktestArtifactKind, path: string, sizeBytes?: bigint, contentType?: string, createdAt: string, };
