// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestDataSourceFilters } from "./BacktestDataSourceFilters";
import type { BacktestDataSourceKind } from "./BacktestDataSourceKind";

export type BacktestDataSource = { id: string, kind: BacktestDataSourceKind, label: string, count: number, filters?: BacktestDataSourceFilters, };
