// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grader source — where this grader came from when it was added to
 * the recipe. Determines the chip copy ("proposed" vs "library" vs
 * "custom" vs "dataset").
 */
export type BacktestGraderSource = "proposed" | "library" | "custom" | "dataset";
