// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestDataScenarioKind } from "./BacktestDataScenarioKind";
import type { BacktestScenarioBucket } from "./BacktestScenarioBucket";

export type BacktestDataScenario = { id: string, kind: BacktestDataScenarioKind, label: string, count: number, bucket?: BacktestScenarioBucket, confidence?: number, accepted?: boolean, clusterLabel?: string, clusterId?: string, };
