// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `list`      — manager landing page: table of past / scheduled /
 *               draft backtests + "+ New backtest".
 * `configure` — the directional pipeline (steps 01..04) for a single
 *               run.
 * `running`   — live progress for a launched run.
 * `results`   — verdict, metrics, divergences for a finished run.
 */
export type BacktestStage = "list" | "configure" | "running" | "results";
