// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row projection of `"BacktestTrialReward"`. The repo typically
 * returns a `HashMap<String, f64>` for rendering, but exporting the
 * row itself lets the CLI inspector show provenance (which grader
 * scored which key).
 */
export type BacktestTrialRewardRecord = { trialId: string, key: string, value: number, graderId?: string, createdAt: string, };
