// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to the environment a run will execute in. Mirrors the
 * shape used by `EnvironmentsManager` (`SandboxEnvironment`) but
 * without the heavy detail snapshot — the recipe only needs the
 * identity + status to render summary chrome.
 */
export type BacktestEnvironmentRef = { id: string, label: string, snapshotId?: string, snapshotLabel?: string, 
/**
 * Mirror of `SandboxRuntimeStatus` strings ("started", "stopped",
 * …). Kept loose so callers don't need to import the environments
 * package.
 */
status?: string, 
/**
 * Whether this environment is a freshly cloned ephemeral sandbox
 * or a saved long-lived environment.
 */
ephemeral?: boolean, };
