// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dataset reference rendered inside the recipe. Distinct from
 * `domain::datasets::Dataset` (the catalog row) — this carries only
 * the identity + size metadata the recipe surface needs.
 */
export type BacktestDataset = { id: string, label: string, 
/**
 * Number of cases in the dataset.
 */
cases: number, source: string, 
/**
 * ISO timestamp of the most recent dataset update.
 */
updated: string, };
