// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-metric row rendered in the Results metrics table. `rows` keys
 * match `BacktestAgent.id`.
 */
export type BacktestMetric = { id: string, label: string, unit: string, 
/**
 * Whether higher numbers are better — drives the delta tone.
 */
higher: boolean, 
/**
 * Baseline value the comparison column anchors against.
 */
baseline: number, rows: { [key in string]?: number }, };
