// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestDataKind } from "./BacktestDataKind";
import type { BacktestDataScenario } from "./BacktestDataScenario";
import type { BacktestDataSource } from "./BacktestDataSource";

export type BacktestData = { kind: BacktestDataKind, 
/**
 * Populated only when `kind == "dataset"`.
 */
dataset?: string, datasetLabel?: string, sources: Array<BacktestDataSource>, scenarios: Array<BacktestDataScenario>, 
/**
 * Optional name the user wants to save this composed dataset as.
 * `null` (vs absent) tells the UI the user opted out of saving.
 */
savedAs?: string | null, };
