// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cluster bucket emitted by the data-science layer when looking for
 * missing scenarios in a dataset.
 */
export type BacktestScenarioBucket = "captured" | "adjacent" | "emerging" | "edge";
