// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrialException } from "./TrialException";
import type { TrialStatus } from "./TrialStatus";
import type { TrialTimings } from "./TrialTimings";

/**
 * Row projection of `"BacktestTrial"`.
 */
export type BacktestTrialRecord = { id: string, jobId: string, tenantId: string, agentId: string, agentLabel: string, isBaseline: boolean, caseId: string, caseCluster?: string, status: TrialStatus, timings: TrialTimings, durationMs?: number, sandboxId?: string, exception?: TrialException, attempt: number, createdAt: string, updatedAt: string, };
