// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestGraderKind } from "./BacktestGraderKind";
import type { BacktestGraderSource } from "./BacktestGraderSource";
import type { BacktestGraderWeight } from "./BacktestGraderWeight";

export type BacktestGrader = { id: string, label: string, kind: BacktestGraderKind, weight: BacktestGraderWeight, source: BacktestGraderSource, 
/**
 * Optional human-readable explanation of why this grader was
 * proposed.
 */
evidence?: string, };
