// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Insert payload for `BacktestTrialRepository::create`.
 */
export type CreateBacktestTrialInput = { jobId: string, tenantId: string, agentId: string, agentLabel: string, isBaseline: boolean, caseId: string, caseCluster?: string, };
