// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestJobMode } from "./BacktestJobMode";
import type { RetryConfig } from "./RetryConfig";
import type { SandboxDriver } from "./SandboxDriver";

/**
 * Insert payload accepted by `BacktestJobRepository::create`. The
 * orchestrator typically builds this from a `JobConfig`; the API
 * layer accepts a `JobConfig` directly and translates.
 */
export type CreateBacktestJobInput = { tenantId: string, name: string, mode: BacktestJobMode, recipe: Record<string, unknown>, nConcurrent: number, sandboxDriver: SandboxDriver, retryConfig?: RetryConfig, createdBy?: string, scheduledFor?: string, };
