// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktestRecipe } from "./BacktestRecipe";
import type { RetryConfig } from "./RetryConfig";
import type { SandboxDriver } from "./SandboxDriver";

/**
 * User-submitted job configuration. Persisted into
 * `BacktestJob.recipe` (the inline `BacktestRecipe`) plus a few
 * orchestrator-level columns (`nConcurrent`, `sandboxDriver`,
 * `retryConfig`).
 */
export type JobConfig = { recipe: BacktestRecipe, nConcurrent: number, sandboxDriver: SandboxDriver, retryConfig?: RetryConfig, scheduledFor?: string, };
