// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the
 * `status` column in `migrations/013_create_backtest_runtime.sql`.
 */
export type JobStatus = "pending" | "running" | "succeeded" | "failed" | "cancelled";
