// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retry policy applied to transient trial failures (network errors,
 * sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass
 * `null` on the wire (`None` here) to fall back to defaults.
 */
export type RetryConfig = { maxRetries: number, minWaitSec: number, maxWaitSec: number, waitMultiplier: number, 
/**
 * When set, only exception kinds in this list trigger a retry.
 * `None` means "retry every transient kind".
 */
includeExceptions?: Array<string>, 
/**
 * Exception kinds that explicitly should not be retried even if
 * otherwise matched by `include_exceptions`.
 */
excludeExceptions?: Array<string>, };
