// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sandbox driver picked at submit time. Echoed onto the
 * `BacktestJob.sandboxDriver` column. The orchestrator reads this to
 * pick the implementation behind the `Sandbox` trait (Phase 1).
 */
export type SandboxDriver = "docker" | "daytona" | "mock";
