// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of a single `BacktestTrial` (one (case × agent)
 * cell).
 */
export type TrialStatus = "pending" | "setup" | "running" | "verifying" | "succeeded" | "failed" | "cancelled";
