// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-phase timing bookkeeping. Each pair is `(started_at,
 * finished_at)`; `None` until that phase starts/ends.
 */
export type TrialTimings = { envSetupStartedAt?: string, envSetupFinishedAt?: string, agentSetupStartedAt?: string, agentSetupFinishedAt?: string, agentRunStartedAt?: string, agentRunFinishedAt?: string, verifierStartedAt?: string, verifierFinishedAt?: string, };
