// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase of execution emitted on the SSE stream as the trial progresses.
 * Distinct from `TrialStatus` — `TrialPhase` is fine-grained progress
 * inside the lifecycle, `TrialStatus` is the persisted summary.
 */
export type TrialPhase = "queued" | "environment-start" | "environment-ready" | "agent-setup" | "agent-running" | "verifier-running" | "artifact-collection" | "cleanup" | "done";
