// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrialException } from "./TrialException";
import type { TrialStatus } from "./TrialStatus";
import type { TrialTimings } from "./TrialTimings";

/**
 * Final result of a single trial. Multi-key reward shape mirrors the
 * `BacktestTrialReward` table (one row per key) and Harbor's
 * `VerifierResult.rewards: dict[str, float]`.
 */
export type TrialResult = { trialId: string, status: TrialStatus, rewards: { [key in string]?: number }, timings: TrialTimings, 
/**
 * Aggregate trial duration (`agent_run_finished_at - env_setup_started_at`)
 * once a terminal status is reached.
 */
durationMs?: number, exception?: TrialException, };
