// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Captured exception info for a failed trial. Mirrors Harbor's
 * `ExceptionInfo` — kind for routing/retry, message for humans.
 */
export type TrialException = { kind: string, message: string, };
