// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { TrialException } from "./TrialException";
import type { TrialPhase } from "./TrialPhase";
import type { TrialStatus } from "./TrialStatus";

/**
 * Event emitted by the orchestrator on its broadcast channel; the SSE
 * handler at `/api/platform/backtests/jobs/:id/stream` re-emits these
 * to the dashboard + CLI. Variants match the dashboard's
 * `BacktestsEvent` plus per-trial fine grain.
 */
export type TrialEvent = { "kind": "job-started", job_id: string, } | { "kind": "trial-phase-changed", job_id: string, trial_id: string, phase: TrialPhase, } | { "kind": "trial-rewards-recorded", job_id: string, trial_id: string, rewards: { [key in string]?: number }, } | { "kind": "trial-finished", job_id: string, trial_id: string, status: TrialStatus, exception?: TrialException, } | { "kind": "job-finished", job_id: string, status: JobStatus, verdict?: string, };
