// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureFlagKey } from "./FeatureFlagKey";
import type { FeatureFlagScope } from "./FeatureFlagScope";

export type FeatureFlagOverride = { id: string, flagKey: FeatureFlagKey, scopeType: FeatureFlagScope, scopeId: string, enabled: boolean, reason: string | null, variant: string | null, rolloutPercentage: number | null, createdAt: string, updatedAt: string, };
