// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

export type AgentEndpointConfig = { id: string, tenantId: string, endpointUrl: string | null, authType: string, authHeaderName: string | null, authSecretEncrypted: string | null, basicUsername: string | null, customHeadersJson: JsonValue | null, createdAt: string, updatedAt: string, };
