// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

export type AuditLog = { id: string, tenantId: string, runId: string | null, eventId: string | null, invocationId: string | null, action: string, actor: string | null, payload: JsonValue | null, createdAt: string, };
