// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type Invitation = { id: string, tenantId: string, email: string, role: UserRole, token: string, invitedBy: string, expiresAt: string, acceptedAt: string | null, createdAt: string, };
