// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

export type Run = { id: string, tenantId: string, workflowId: string | null, eventId: string, invocationId: string, mode: string, status: string, eventSnapshot: JsonValue | null, contextPointers: JsonValue | null, agentRequest: JsonValue | null, agentResponse: JsonValue | null, humanDecision: JsonValue | null, createdAt: string, updatedAt: string, };
