// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipStatus } from "./MembershipStatus";
import type { UserRole } from "./UserRole";

export type TenantMembership = { id: string, userId: string, tenantId: string, role: UserRole, status: MembershipStatus, createdAt: string, updatedAt: string, };
