// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type User = { id: string, email: string, name: string | null, password: string | null, authProvider: string, role: UserRole, tenantId: string, 
/**
 * Linked WorkOS user id (`user_…`). Populated by the importer for
 * pre-existing accounts and at JIT-create time for new accounts.
 */
workosUserId: string | null, 
/**
 * Mirror of WorkOS `emailVerified` state. Mirrored at JIT-create and
 * SCIM-sync time so audit code can answer "did this person ever verify
 * their email?" without round-tripping to WorkOS.
 */
emailVerifiedAt: string | null, 
/**
 * Free-form provenance tag. One of `self_serve`, `invite`, `scim`,
 * `import`. Used by the F.2 admin user-detail surface and to bucket
 * audit reports across provisioning paths.
 */
createdVia: string | null, createdAt: string, updatedAt: string, };
