// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureAccessSnapshot } from "../feature-access/FeatureAccessSnapshot";
import type { FeatureFlagOverride } from "../feature-access/FeatureFlagOverride";
import type { Tenant } from "../saas/Tenant";

export type AdminTenantFeatureAccessResponse = { tenant: Tenant | null, access: FeatureAccessSnapshot, overrides: Array<FeatureFlagOverride>, };
