// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEndpointConfig } from "../saas/AgentEndpointConfig";

export type AgentEndpointResponse = { config: AgentEndpointConfig | null, };
