// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "../saas/Connection";

export type ConnectionListResponse = { connections: Array<Connection>, };
