// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../serde_json/JsonValue";

export type CreateRunRequest = { eventId: string, invocationId: string, mode: string | null, workflowId: string | null, eventSnapshot: JsonValue | null, contextPointers: JsonValue | null, };
