// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardStatsResponse = { totalRuns: number, pendingRuns: number, completedRuns: number, failedRuns: number, totalConnections: number, activeConnections: number, };
