// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLog } from "../saas/AuditLog";

export type DashboardActivityResponse = { activity: Array<AuditLog>, };
