// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureFlagDefinition } from "../feature-access/FeatureFlagDefinition";

export type FeatureFlagDefinitionsResponse = { flags: Array<FeatureFlagDefinition>, };
