// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureAccessSnapshot } from "../feature-access/FeatureAccessSnapshot";

export type FeatureAccessResponse = { access: FeatureAccessSnapshot, };
