// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "../saas/Run";

export type ListRunsResponse = { runs: Array<Run>, total: number, limit: number, offset: number, };
