// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxAiChatMessage } from "../sandbox/SandboxAiChatMessage";
import type { SandboxEdgeDto } from "../sandbox/SandboxEdgeDto";
import type { SandboxNodeDto } from "../sandbox/SandboxNodeDto";

export type SandboxAiChatRequest = { prompt: string, nodes: Array<SandboxNodeDto>, edges: Array<SandboxEdgeDto>, selectedNodeId: string | null, recentMessages: Array<SandboxAiChatMessage>, };
