// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEditCommand } from "../sandbox/GraphEditCommand";
import type { GraphEditPreview } from "../sandbox/GraphEditPreview";
import type { GraphEditValidationError } from "../sandbox/GraphEditValidationError";
import type { SandboxValidationResponse } from "../sandbox/SandboxValidationResponse";

export type SandboxAiChatResponse = { assistantMessage: string, commands: Array<GraphEditCommand>, preview: GraphEditPreview, validation: SandboxValidationResponse, errors: Array<GraphEditValidationError>, };
