// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tenant } from "../saas/Tenant";

export type TenantResponse = { tenant: Tenant | null, };
