// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAgentEndpointRequest = { endpointUrl: string | null, authType: string | null, authHeaderName: string | null, basicUsername: string | null, };
