// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentWorkflowNode } from "../../types/agents/AgentWorkflowNode";

export const AgentWorkflowNodeSchema = z.object({ "id": z.string(), "kind": z.enum(["input","tool","model","branch","output"]), "label": z.string(), "toolName": z.union([z.string().describe("Optional tool name reference for tool nodes."), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentWorkflowNodeInferred = z.infer<typeof AgentWorkflowNodeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentWorkflowNodeDriftCheck = _AgentWorkflowNodeInferred & AgentWorkflowNode;
