// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentToolCall } from "../../types/agents/AgentToolCall";

export const AgentToolCallSchema = z.object({ "argsHash": z.union([z.string(), z.null()]).optional(), "argsPreview": z.union([z.record(z.string(), z.any()).describe("Optional small preview of the tool args."), z.null()]).optional(), "callId": z.string(), "durationMs": z.union([z.number().int().gte(0), z.null()]).optional(), "error": z.union([z.object({ "message": z.string(), "name": z.union([z.string(), z.null()]).optional(), "stack": z.union([z.string(), z.null()]).optional() }), z.null()]).optional(), "finishedAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "resultHash": z.union([z.string(), z.null()]).optional(), "resultPreview": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "startedAt": z.string().datetime({ offset: true }), "status": z.enum(["started","success","error"]), "toolName": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentToolCallInferred = z.infer<typeof AgentToolCallSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentToolCallDriftCheck = _AgentToolCallInferred & AgentToolCall;
