// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentRunUsage } from "../../types/agents/AgentRunUsage";

export const AgentRunUsageSchema = z.object({ "cachedInputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "inputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "outputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "reasoningTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "totalTokens": z.union([z.number().int().gte(0), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentRunUsageInferred = z.infer<typeof AgentRunUsageSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentRunUsageDriftCheck = _AgentRunUsageInferred & AgentRunUsage;
