// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentPolicy } from "../../types/agents/AgentPolicy";

export const AgentPolicySchema = z.object({ "allowedTools": z.union([z.array(z.string()), z.null()]).optional(), "approvalRequired": z.union([z.array(z.string()), z.null()]).optional(), "maxSteps": z.union([z.number().int().gte(0), z.null()]).optional(), "metadata": z.union([z.record(z.string(), z.any()), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentPolicyInferred = z.infer<typeof AgentPolicySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentPolicyDriftCheck = _AgentPolicyInferred & AgentPolicy;
