// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentManifestDiffRow } from "../../types/agents/AgentManifestDiffRow";

export const AgentManifestDiffRowSchema = z.object({ "after": z.any(), "before": z.any(), "domain": z.enum(["agent.root","prompt","model.contract","provider.options","tool.contract","runtime.policy","dependency","knowledge.contract","workflow.graph","effective.run","provider.observation","operational","output"]).describe("The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time)."), "path": z.string().describe("JSON path within the domain."), "unchanged": z.boolean().describe("True when before/after are deep-equal.") })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentManifestDiffRowInferred = z.infer<typeof AgentManifestDiffRowSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentManifestDiffRowDriftCheck = _AgentManifestDiffRowInferred & AgentManifestDiffRow;
