// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentKnowledgeSource } from "../../types/agents/AgentKnowledgeSource";

export const AgentKnowledgeSourceSchema = z.object({ "href": z.union([z.string().describe("Optional jump-out link."), z.null()]).optional(), "id": z.string(), "kind": z.enum(["vector","doc","table","graph"]), "label": z.string(), "sizeLabel": z.union([z.string().describe("Optional human-readable size hint, e.g. \"12.4k docs\"."), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentKnowledgeSourceInferred = z.infer<typeof AgentKnowledgeSourceSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentKnowledgeSourceDriftCheck = _AgentKnowledgeSourceInferred & AgentKnowledgeSource;
