// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentKnowledgeKind } from "../../types/agents/AgentKnowledgeKind";

export const AgentKnowledgeKindSchema = z.enum(["vector","doc","table","graph"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentKnowledgeKindInferred = z.infer<typeof AgentKnowledgeKindSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentKnowledgeKindDriftCheck = _AgentKnowledgeKindInferred & AgentKnowledgeKind;
