// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentModelDescriptor } from "../../types/agents/AgentModelDescriptor";

export const AgentModelDescriptorSchema = z.object({ "label": z.string(), "modelId": z.union([z.string(), z.null()]).optional(), "provider": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentModelDescriptorInferred = z.infer<typeof AgentModelDescriptorSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentModelDescriptorDriftCheck = _AgentModelDescriptorInferred & AgentModelDescriptor;
