// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentWorkflowEdge } from "../../types/agents/AgentWorkflowEdge";

export const AgentWorkflowEdgeSchema = z.object({ "from": z.string(), "label": z.union([z.string().describe("Optional short label rendered along the edge."), z.null()]).optional(), "to": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentWorkflowEdgeInferred = z.infer<typeof AgentWorkflowEdgeSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentWorkflowEdgeDriftCheck = _AgentWorkflowEdgeInferred & AgentWorkflowEdge;
