// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentContractPreview } from "../../types/agents/AgentContractPreview";

export const AgentContractPreviewSchema = z.object({ "example": z.any().describe("Representative example payload.").optional(), "schemaSummary": z.union([z.string().describe("One-line shape summary."), z.null()]).optional() }).describe("Compact preview of an input or output contract for the artifact's Capabilities section.")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentContractPreviewInferred = z.infer<typeof AgentContractPreviewSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentContractPreviewDriftCheck = _AgentContractPreviewInferred & AgentContractPreview;
