// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentSummary } from "../../types/agents/AgentSummary";

export const AgentSummarySchema = z.object({ "capabilityTags": z.union([z.array(z.string()), z.null()]).optional(), "category": z.union([z.string(), z.null()]).optional(), "description": z.union([z.string(), z.null()]).optional(), "environment": z.union([z.string(), z.null()]).optional(), "framework": z.enum(["vercel-ai-sdk","openai-agents","langchain","mastra","langchain-python","llamaindex","crewai","smolagents","pydantic-ai","strands","google-adk","openai-agents-python","autogen"]).describe("Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.)."), "lastDriftAt": z.union([z.string().datetime({ offset: true }).describe("Last drift event, if any."), z.null()]).optional(), "lastRunAt": z.union([z.string().datetime({ offset: true }), z.null()]).optional(), "latestVersion": z.string(), "model": z.object({ "label": z.string(), "modelId": z.union([z.string(), z.null()]).optional(), "provider": z.union([z.string(), z.null()]).optional() }), "modelLabel": z.string(), "name": z.string(), "owner": z.union([z.string(), z.null()]).optional(), "personaSummary": z.union([z.string(), z.null()]).optional(), "playgroundUrl": z.union([z.string(), z.null()]).optional(), "purpose": z.union([z.string(), z.null()]).optional(), "runbookUrl": z.union([z.string(), z.null()]).optional(), "successRate": z.number(), "totalRuns": z.number().int().gte(0), "versionCount": z.number().int().gte(0) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentSummaryInferred = z.infer<typeof AgentSummarySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentSummaryDriftCheck = _AgentSummaryInferred & AgentSummary;
