// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentWorkflowGraph } from "../../types/agents/AgentWorkflowGraph";

export const AgentWorkflowGraphSchema = z.object({ "edges": z.array(z.object({ "from": z.string(), "label": z.union([z.string().describe("Optional short label rendered along the edge."), z.null()]).optional(), "to": z.string() })), "nodes": z.array(z.object({ "id": z.string(), "kind": z.enum(["input","tool","model","branch","output"]), "label": z.string(), "toolName": z.union([z.string().describe("Optional tool name reference for tool nodes."), z.null()]).optional() })) })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentWorkflowGraphInferred = z.infer<typeof AgentWorkflowGraphSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentWorkflowGraphDriftCheck = _AgentWorkflowGraphInferred & AgentWorkflowGraph;
