// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentRunOperation } from "../../types/agents/AgentRunOperation";

export const AgentRunOperationSchema = z.enum(["generate","stream"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentRunOperationInferred = z.infer<typeof AgentRunOperationSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentRunOperationDriftCheck = _AgentRunOperationInferred & AgentRunOperation;
