// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentPreparedCall } from "../../types/agents/AgentPreparedCall";

export const AgentPreparedCallSchema = z.object({ "activeTools": z.union([z.array(z.string()), z.null()]).optional(), "hash": z.string(), "providerOptionsHash": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentPreparedCallInferred = z.infer<typeof AgentPreparedCallSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentPreparedCallDriftCheck = _AgentPreparedCallInferred & AgentPreparedCall;
