// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentRunStatus } from "../../types/agents/AgentRunStatus";

export const AgentRunStatusSchema = z.enum(["started","success","error"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentRunStatusInferred = z.infer<typeof AgentRunStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentRunStatusDriftCheck = _AgentRunStatusInferred & AgentRunStatus;
