// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentFramework } from "../../types/agents/AgentFramework";

export const AgentFrameworkSchema = z.enum(["vercel-ai-sdk","openai-agents","langchain","mastra","langchain-python","llamaindex","crewai","smolagents","pydantic-ai","strands","google-adk","openai-agents-python","autogen"]).describe("Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.).")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentFrameworkInferred = z.infer<typeof AgentFrameworkSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentFrameworkDriftCheck = _AgentFrameworkInferred & AgentFramework;
