// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentWorkflowNodeKind } from "../../types/agents/AgentWorkflowNodeKind";

export const AgentWorkflowNodeKindSchema = z.enum(["input","tool","model","branch","output"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentWorkflowNodeKindInferred = z.infer<typeof AgentWorkflowNodeKindSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentWorkflowNodeKindDriftCheck = _AgentWorkflowNodeKindInferred & AgentWorkflowNodeKind;
