// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentToolDefinition } from "../../types/agents/AgentToolDefinition";

export const AgentToolDefinitionSchema = z.object({ "description": z.union([z.string(), z.null()]).optional(), "inputSchemaHash": z.union([z.string(), z.null()]).optional(), "inputSchemaPreview": z.union([z.record(z.string(), z.any()).describe("Optional small input-schema preview rendered in the Tools tab."), z.null()]).optional(), "metadata": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "name": z.string() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentToolDefinitionInferred = z.infer<typeof AgentToolDefinitionSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentToolDefinitionDriftCheck = _AgentToolDefinitionInferred & AgentToolDefinition;
