// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentRunError } from "../../types/agents/AgentRunError";

export const AgentRunErrorSchema = z.object({ "message": z.string(), "name": z.union([z.string(), z.null()]).optional(), "stack": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentRunErrorInferred = z.infer<typeof AgentRunErrorSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentRunErrorDriftCheck = _AgentRunErrorInferred & AgentRunError;
