// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentDriftEntry } from "../../types/agents/AgentDriftEntry";

export const AgentDriftEntrySchema = z.object({ "after": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "artifactId": z.string(), "before": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "observedAt": z.string().datetime({ offset: true }), "runId": z.string(), "summary": z.string().describe("Short verb summarizing the change.") })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentDriftEntryInferred = z.infer<typeof AgentDriftEntrySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentDriftEntryDriftCheck = _AgentDriftEntryInferred & AgentDriftEntry;
