// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentProvenance } from "../../types/agents/AgentProvenance";

export const AgentProvenanceSchema = z.object({ "aiSdkVersion": z.union([z.string(), z.null()]).optional(), "createdAt": z.string().datetime({ offset: true }), "dependencyLockHash": z.union([z.string(), z.null()]).optional(), "frameworkVersion": z.union([z.string(), z.null()]).optional(), "gitSha": z.union([z.string(), z.null()]).optional(), "publishedBy": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentProvenanceInferred = z.infer<typeof AgentProvenanceSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentProvenanceDriftCheck = _AgentProvenanceInferred & AgentProvenance;
