// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentRunResponse } from "../../types/agents/AgentRunResponse";

export const AgentRunResponseSchema = z.object({ "bodyHash": z.union([z.string(), z.null()]).optional(), "finishReason": z.union([z.string(), z.null()]).optional(), "headers": z.union([z.record(z.string(), z.string()).describe("Subset of headers preserved for the run drawer."), z.null()]).optional(), "id": z.union([z.string(), z.null()]).optional(), "modelId": z.union([z.string(), z.null()]).optional(), "modelMetadata": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "providerMetadata": z.union([z.record(z.string(), z.any()), z.null()]).optional(), "usage": z.union([z.object({ "cachedInputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "inputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "outputTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "reasoningTokens": z.union([z.number().int().gte(0), z.null()]).optional(), "totalTokens": z.union([z.number().int().gte(0), z.null()]).optional() }), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentRunResponseInferred = z.infer<typeof AgentRunResponseSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentRunResponseDriftCheck = _AgentRunResponseInferred & AgentRunResponse;
