// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { AgentVersionStatus } from "../../types/agents/AgentVersionStatus";

export const AgentVersionStatusSchema = z.enum(["current","stable","deprecated","draft"])

// Static drift guard — fails compilation if Rust + Zod diverge.
type _AgentVersionStatusInferred = z.infer<typeof AgentVersionStatusSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _AgentVersionStatusDriftCheck = _AgentVersionStatusInferred & AgentVersionStatus;
