// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { HashIndexEntry } from "../../types/agents/HashIndexEntry";

export const HashIndexEntrySchema = z.object({ "artifactId": z.union([z.string(), z.null()]).optional(), "framework": z.union([z.enum(["vercel-ai-sdk","openai-agents","langchain","mastra","langchain-python","llamaindex","crewai","smolagents","pydantic-ai","strands","google-adk","openai-agents-python","autogen"]).describe("Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.)."), z.null()]).optional(), "hash": z.string(), "kind": z.enum(["agent.root","prompt","model.contract","provider.options","tool.contract","runtime.policy","dependency","knowledge.contract","workflow.graph","effective.run","provider.observation","operational","output"]).describe("The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time)."), "observedAt": z.string().datetime({ offset: true }), "path": z.string(), "preview": z.union([z.string().describe("Stringified preview of the value rendered next to the hash."), z.null()]).optional(), "runId": z.union([z.string(), z.null()]).optional() })

// Static drift guard — fails compilation if Rust + Zod diverge.
type _HashIndexEntryInferred = z.infer<typeof HashIndexEntrySchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _HashIndexEntryDriftCheck = _HashIndexEntryInferred & HashIndexEntry;
