// This file was generated by packages/chronicle/scripts/gen-zod.ts. Do not edit manually.
import { z } from "zod";
import type { HashDomain } from "../../types/agents/HashDomain";

export const HashDomainSchema = z.enum(["agent.root","prompt","model.contract","provider.options","tool.contract","runtime.policy","dependency","knowledge.contract","workflow.graph","effective.run","provider.observation","operational","output"]).describe("The 13 hash domains the wrapper tracks. The first eight describe the artifact (config-time); the last five describe a run (observed at call-time).")

// Static drift guard — fails compilation if Rust + Zod diverge.
type _HashDomainInferred = z.infer<typeof HashDomainSchema>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type _HashDomainDriftCheck = _HashDomainInferred & HashDomain;
