"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _profile_card from './profile-card.bones.json'
import _env_card from './env-card.bones.json'

configureBoneyard({"color":"var(--c-wash-3)","darkColor":"var(--c-wash-3)","animate":"pulse","transition":200})

registerBones({
  "profile-card": _profile_card,
  "env-card": _env_card,
})
